"""homelab-mcp-control domain tools.

Generated by tools/phase_1_0_split_server.py from
mcp/src/homelab_mcp/server.py at the Phase 1.0 refactor. Tool source is
byte-faithful with the pre-split monolith. Edit the generator (and the
inventory) rather than hand-patching this file.
"""

from __future__ import annotations

# --- Imports (mirrors original server.py for tool body fidelity) ---
import os

import subprocess

from homelab_mcp.app import create_mcp

from homelab_mcp.audit import audit as _write_audit

from homelab_mcp.audit import configure_audit_logger

from homelab_mcp.clients import (
    ServarrClient,
    QbtClient,
    PlexClient,
    HomebridgeClient,
    Mylar3Client,
    get_sonarr_config,
    get_radarr_config,
    get_lidarr_config,
    get_readarr_config,
    get_mylar3_config,
    get_prowlarr_config,
    get_qbt_config,
    get_plex_config,
    get_homebridge_config,
    get_scrypted_config,
    get_dirigera_config,
    get_unifi_config,
    env,
)

from homelab_mcp.policy import WRITE_TOOLS as _POLICY_WRITE_TOOLS

from homelab_mcp.policy import check_readonly as _policy_check_readonly

from homelab_mcp.settings import (
    audit_log_path,
    cf_allowed_zones,
    cf_default_zone,
    env_flag,
    homelab_ingress_ip,
    ingress_host_re,
    require_env,
)

import json as _json

import re as _re

from datetime import datetime as _dt, timedelta as _td, timezone as _tz

import asyncio as _aio

import json as _json


# --- Shared runtime state: registers tools onto the singleton mcp instance ---
from homelab_mcp._runtime import (  # noqa: F401  imports used by tool bodies
    _AUDIT_LOG_PATH,
    _AUDIT_TOOL_RE,
    _DNS_NAME_RE,
    _DURATION_RE,
    _IMAGE_RE,
    _K8S_NAME_RE,
    _PROWLARR_DEF_RE,
    _READONLY,
    _WRITE_TOOLS,
    _apple_connect,
    _apple_devices_map,
    _apple_run,
    _audit,
    _audit_logger,
    _cf_get,
    _cf_token,
    _check_readonly,
    _client_summary,
    _clients,
    _dev_summary,
    _dirigera,
    _find_light,
    _flux,
    _homebridge,
    _kube,
    _lidarr,
    _mylar3,
    _need_dirigera,
    _plex,
    _prowlarr,
    _qbt,
    _radarr,
    _readarr,
    _resolve_mac,
    _sonarr,
    _ssh_exec,
    _unifi_run,
    _validate_duration,
    _validate_image,
    _validate_k8s_name,
    mcp,
)

# --- Domain tools (29) ---

@mcp.tool()
def sonarr_search_missing() -> dict:
    """Trigger a search for all missing episodes in Sonarr."""
    _audit("sonarr_search_missing", {})
    _check_readonly("sonarr_search_missing")
    c = _sonarr()
    result = c.post("/command", json={"name": "MissingEpisodeSearch"})
    return {"command_id": result.get("id"), "status": result.get("status")}


@mcp.tool()
def radarr_search_missing() -> dict:
    """Trigger a search for all missing movies in Radarr."""
    _audit("radarr_search_missing", {})
    _check_readonly("radarr_search_missing")
    c = _radarr()
    result = c.post("/command", json={"name": "MissingMoviesSearch"})
    return {"command_id": result.get("id"), "status": result.get("status")}


@mcp.tool()
def lidarr_search_missing() -> dict:
    """Trigger a search for all missing albums in Lidarr."""
    _audit("lidarr_search_missing", {})
    _check_readonly("lidarr_search_missing")
    c = _lidarr()
    result = c.post("/command", json={"name": "MissingAlbumSearch"})
    return {"command_id": result.get("id"), "status": result.get("status")}


@mcp.tool()
def readarr_search_missing() -> dict:
    """Trigger a search for all missing books in Readarr."""
    _audit("readarr_search_missing", {})
    _check_readonly("readarr_search_missing")
    c = _readarr()
    result = c.post("/command", json={"name": "MissingBookSearch"})
    return {"command_id": result.get("id"), "status": result.get("status")}


@mcp.tool()
def mylar3_search_missing() -> dict:
    """Trigger Mylar3's force-search across all wanted issues."""
    _audit("mylar3_search_missing", {})
    _check_readonly("mylar3_search_missing")
    c = _mylar3()
    res = c.call("forceSearch")
    return {"result": res if isinstance(res, str) else res.get("data", res)}


@mcp.tool()
def qbt_pause(hashes: str = "all") -> dict:
    """Pause torrent(s). Pass hash(es) separated by | or 'all'."""
    _audit("qbt_pause", {"hashes": hashes})
    _check_readonly("qbt_pause")
    c = _qbt()
    c.post("/torrents/stop", data={"hashes": hashes})
    return {"paused": hashes}


@mcp.tool()
def qbt_resume(hashes: str = "all") -> dict:
    """Resume torrent(s). Pass hash(es) separated by | or 'all'."""
    _audit("qbt_resume", {"hashes": hashes})
    _check_readonly("qbt_resume")
    c = _qbt()
    c.post("/torrents/start", data={"hashes": hashes})
    return {"resumed": hashes}


@mcp.tool()
def plex_scan_library(library_key: str) -> dict:
    """Trigger a library scan in Plex. Pass the library key (from plex_libraries)."""
    _audit("plex_scan_library", {"library_key": library_key})
    _check_readonly("plex_scan_library")
    c = _plex()
    c.put(f"/library/sections/{library_key}/refresh")
    return {"scanning": library_key}


@mcp.tool()
def plex_maintenance() -> dict:
    """Run Plex maintenance: optimize database, clean bundles, empty trash."""
    _audit("plex_maintenance", {})
    _check_readonly("plex_maintenance")
    c = _plex()
    c.put("/library/optimize")
    c.put("/library/clean/bundles")
    # empty trash per library
    libs = c.get("/library/sections")
    for lib in libs.get("MediaContainer", {}).get("Directory", []):
        c.put(f"/library/sections/{lib['key']}/emptyTrash")
    return {"optimized": True, "cleaned_bundles": True, "emptied_trash": True}


@mcp.tool()
def kube_restart(deployment: str, ns: str = "default") -> str:
    """Rollout restart a Kubernetes deployment. This is the only mutating kube tool."""
    _check_readonly("kube_restart")
    _validate_k8s_name(deployment, "deployment")
    _validate_k8s_name(ns, "namespace")
    _audit("kube_restart", {"deployment": deployment, "ns": ns})
    return _kube(f"rollout restart deployment/{deployment} -n {ns}")


@mcp.tool()
def kube_image_can_pull(image: str, timeout: int = 60) -> dict:
    """Test if the cluster can pull a container image by running a throwaway pod."""
    _audit("kube_image_can_pull", {"image": image, "timeout": timeout})
    _check_readonly("kube_image_can_pull")
    _validate_image(image)
    import uuid
    pod_name = f"mcp-pull-test-{uuid.uuid4().hex[:8]}"
    try:
        _kube(f"run {pod_name} --image={image} --restart=Never --command -- /bin/true")
        _kube(
            f"wait pod/{pod_name} -n default --for=condition=Ready --timeout={int(timeout)}s",
            timeout=int(timeout) + 10,
        )
        return {"can_pull": True, "image": image}
    except RuntimeError as e:
        return {"can_pull": False, "image": image, "error": str(e)}
    finally:
        try:
            _kube(f"delete pod {pod_name} -n default --ignore-not-found=true")
        except Exception:
            pass


@mcp.tool()
def flux_reconcile(target: str = "all") -> str:
    """Trigger Flux reconciliation. Target: 'all' (source + kustomization), 'source', or a kustomization name."""
    _check_readonly("flux_reconcile")
    _audit("flux_reconcile", {"target": target})
    if target == "all":
        src = _flux("reconcile source git flux-system")
        kust = _flux("reconcile kustomization flux-system")
        return f"Source: {src}\nKustomization: {kust}"
    elif target == "source":
        return _flux("reconcile source git flux-system")
    else:
        _validate_k8s_name(target, "kustomization")
        return _flux(f"reconcile kustomization {target}")


@mcp.tool()
def flux_suspend(kustomization: str = "flux-system") -> str:
    """Suspend a Flux kustomization (pauses reconciliation for hot-fix workflows)."""
    _check_readonly("flux_suspend")
    _validate_k8s_name(kustomization, "kustomization")
    _audit("flux_suspend", {"kustomization": kustomization})
    return _flux(f"suspend kustomization {kustomization}")


@mcp.tool()
def flux_resume(kustomization: str = "flux-system") -> str:
    """Resume a suspended Flux kustomization."""
    _check_readonly("flux_resume")
    _validate_k8s_name(kustomization, "kustomization")
    _audit("flux_resume", {"kustomization": kustomization})
    return _flux(f"resume kustomization {kustomization}")


@mcp.tool()
def dirigera_set_light(name_or_id: str, on: bool | None = None,
                       brightness: int | None = None,
                       color_temperature: int | None = None,
                       hue: int | None = None,
                       saturation: float | None = None) -> dict:
    """Control a light by name or id.
    on: True/False to switch on/off.
    brightness: 1-100.
    color_temperature: kelvin (e.g. 2700-4000 typical range).
    hue (0-360) + saturation (0.0-1.0) for color bulbs."""
    _audit("dirigera_set_light", {"name_or_id": name_or_id, "on": on,
           "brightness": brightness, "color_temperature": color_temperature,
           "hue": hue, "saturation": saturation})
    _check_readonly("dirigera_set_light")
    h = _need_dirigera()
    light = _find_light(h, name_or_id)
    actions: list[str] = []
    if on is not None:
        light.set_light(lamp_on=bool(on)); actions.append(f"on={on}")
    if brightness is not None:
        light.set_light_level(light_level=int(brightness)); actions.append(f"brightness={brightness}")
    if color_temperature is not None:
        light.set_color_temperature(color_temp=int(color_temperature))
        actions.append(f"color_temp={color_temperature}")
    if hue is not None and saturation is not None:
        light.set_light_color(hue=int(hue), saturation=float(saturation))
        actions.append(f"color={hue}/{saturation}")
    return {"id": light.id, "name": light.attributes.custom_name, "applied": actions}


@mcp.tool()
def dirigera_set_outlet(name_or_id: str, on: bool) -> dict:
    """Turn a smart outlet on or off (by name or id)."""
    _audit("dirigera_set_outlet", {"name_or_id": name_or_id, "on": on})
    _check_readonly("dirigera_set_outlet")
    h = _need_dirigera()
    target = next((o for o in h.get_outlets()
                   if o.id == name_or_id or o.attributes.custom_name == name_or_id), None)
    if not target:
        raise RuntimeError(f"Outlet not found: {name_or_id}")
    target.set_on(outlet_on=bool(on))
    return {"id": target.id, "name": target.attributes.custom_name, "is_on": bool(on)}


@mcp.tool()
def dirigera_set_blind(name_or_id: str, target_level: int) -> dict:
    """Move a blind to a target level (0=fully closed, 100=fully open)."""
    _audit("dirigera_set_blind", {"name_or_id": name_or_id, "target_level": target_level})
    _check_readonly("dirigera_set_blind")
    h = _need_dirigera()
    target = next((b for b in h.get_blinds()
                   if b.id == name_or_id or b.attributes.custom_name == name_or_id), None)
    if not target:
        raise RuntimeError(f"Blind not found: {name_or_id}")
    target.set_target_level(target_level=int(target_level))
    return {"id": target.id, "name": target.attributes.custom_name,
            "target_level": int(target_level)}


@mcp.tool()
def dirigera_trigger_scene(name_or_id: str) -> dict:
    """Run a scene by name or id."""
    _audit("dirigera_trigger_scene", {"name_or_id": name_or_id})
    _check_readonly("dirigera_trigger_scene")
    h = _need_dirigera()
    target = next((s for s in h.get_scenes()
                   if s.id == name_or_id or
                   (getattr(s.info, "name", None) == name_or_id)), None)
    if not target:
        raise RuntimeError(f"Scene not found: {name_or_id}")
    target.trigger()
    return {"id": target.id, "name": target.info.name, "triggered": True}


@mcp.tool()
def apple_play_pause(device: str) -> dict:
    """Toggle play/pause on a configured Apple device."""
    _audit("apple_play_pause", {"device": device})
    _check_readonly("apple_play_pause")
    async def _pp():
        atv, _ = await _apple_connect(device)
        try:
            await atv.remote_control.play_pause()
            return {"device": device, "ok": True}
        finally:
            atv.close()
    return _apple_run(_pp())


@mcp.tool()
def apple_volume(device: str, level: float | None = None) -> dict:
    """Get or set volume (0.0-100.0). Omit level to read current value."""
    _audit("apple_volume", {"device": device, "level": level})
    if level is not None:
        _check_readonly("apple_volume")
    async def _vol():
        atv, _ = await _apple_connect(device)
        try:
            if level is None:
                v = atv.audio.volume
                return {"device": device, "volume": v}
            await atv.audio.set_volume(float(level))
            return {"device": device, "volume": float(level)}
        finally:
            atv.close()
    return _apple_run(_vol())


@mcp.tool()
def apple_remote(device: str, key: str) -> dict:
    """Send a remote-control key. Valid keys: menu, home, select, up, down,
    left, right, play, pause, stop, next, previous, top_menu, suspend, wakeup."""
    _audit("apple_remote", {"device": device, "key": key})
    _check_readonly("apple_remote")
    async def _rc():
        atv, _ = await _apple_connect(device)
        try:
            fn = getattr(atv.remote_control, key, None)
            if fn is None:
                raise RuntimeError(f"Unknown remote key: {key}")
            await fn()
            return {"device": device, "key": key, "ok": True}
        finally:
            atv.close()
    return _apple_run(_rc())


@mcp.tool()
def apple_launch_app(device: str, app: str) -> dict:
    """Launch an app on the Apple TV by identifier (e.g. com.netflix.Netflix)
    or by display name (case-insensitive partial match)."""
    _audit("apple_launch_app", {"device": device, "app": app})
    _check_readonly("apple_launch_app")
    async def _launch():
        atv, _ = await _apple_connect(device)
        try:
            target_id = app
            if "." not in app:
                apps = await atv.apps.app_list()
                m = [a for a in apps if app.lower() in a.name.lower()]
                if not m:
                    raise RuntimeError(f"No app matching {app!r}. Try apple_apps() to list.")
                target_id = m[0].identifier
                app_name = m[0].name
            else:
                app_name = app
            await atv.apps.launch_app(target_id)
            return {"device": device, "launched": app_name, "identifier": target_id}
        finally:
            atv.close()
    return _apple_run(_launch())


@mcp.tool()
def apple_run_shortcut(device: str, name: str) -> dict:
    """Run an Apple Shortcut by exact name on the target Apple TV.
    The Shortcut must already exist on iCloud and be enabled for Apple TV.
    This is the gateway to HomeKit scenes — wrap any Home scene in a Shortcut
    and trigger it from here."""
    _audit("apple_run_shortcut", {"device": device, "name": name})
    _check_readonly("apple_run_shortcut")
    async def _run():
        atv, _ = await _apple_connect(device)
        try:
            # pyatv's apps API exposes launch_app; Shortcuts are launched via a
            # special URL scheme: shortcuts://run-shortcut?name=<NAME>
            from urllib.parse import quote
            url = f"shortcuts://run-shortcut?name={quote(name)}"
            await atv.apps.launch_app(url)
            return {"device": device, "shortcut": name, "ok": True}
        finally:
            atv.close()
    return _apple_run(_run())


@mcp.tool()
def unifi_block(name_or_mac: str) -> dict:
    """Block a client from accessing the network (kid bedtime / device quarantine)."""
    _audit("unifi_block", {"name_or_mac": name_or_mac})
    _check_readonly("unifi_block")
    async def _b(controller):
        await controller.clients.update()
        await controller.clients_all.update()
        mac = _resolve_mac(controller, name_or_mac)
        await controller.clients.block(mac)
        return {"mac": mac, "blocked": True}
    return _unifi_run(_b)


@mcp.tool()
def unifi_unblock(name_or_mac: str) -> dict:
    """Lift a network block on a client."""
    _audit("unifi_unblock", {"name_or_mac": name_or_mac})
    _check_readonly("unifi_unblock")
    async def _u(controller):
        await controller.clients.update()
        await controller.clients_all.update()
        mac = _resolve_mac(controller, name_or_mac)
        await controller.clients.unblock(mac)
        return {"mac": mac, "blocked": False}
    return _unifi_run(_u)


@mcp.tool()
def unifi_reconnect(name_or_mac: str) -> dict:
    """Force a wireless client to reconnect (kick from current AP)."""
    _audit("unifi_reconnect", {"name_or_mac": name_or_mac})
    _check_readonly("unifi_reconnect")
    async def _r(controller):
        await controller.clients.update()
        mac = _resolve_mac(controller, name_or_mac)
        await controller.clients.reconnect(mac)
        return {"mac": mac, "reconnected": True}
    return _unifi_run(_r)


@mcp.tool()
def unifi_wlan_set(name: str, enabled: bool) -> dict:
    """Enable or disable an SSID by name."""
    _audit("unifi_wlan_set", {"name": name, "enabled": enabled})
    _check_readonly("unifi_wlan_set")
    async def _s(controller):
        await controller.wlans.update()
        target = next((w for w in controller.wlans.values() if w.name == name), None)
        if not target:
            raise RuntimeError(f"WLAN {name!r} not found")
        if enabled:
            await controller.wlans.enable(target)
        else:
            await controller.wlans.disable(target)
        return {"name": target.name, "enabled": enabled}
    return _unifi_run(_s)


@mcp.tool()
def prowlarr_add_torznab_indexer(
    name: str,
    url: str,
    api_key: str,
    categories: list[int] | None = None,
    definition: str = "Generic Torznab",
) -> dict:
    """Add a Torznab indexer to Prowlarr.

    Scoped to Torznab only (covers ~90% of self-host indexers including most
    private trackers). For other indexer kinds, use the Prowlarr UI directly —
    a generic ``add_indexer`` tool would be ``run_arbitrary_request`` in disguise.

    Args:
        name: Display name (1–64 chars, alnum + space/hyphen/underscore).
        url: Indexer base URL (must be http(s)://).
        api_key: Indexer API key (passed to Prowlarr, not logged in audit).
        categories: Newznab category IDs (defaults to ``[5000]`` = TV).
        definition: Prowlarr definition name; defaults to ``Generic Torznab``.
    """
    _audit("prowlarr_add_torznab_indexer", {"name": name, "url": url})
    _check_readonly("prowlarr_add_torznab_indexer")

    if not name or len(name) > 64 or not _re.match(r'^[a-zA-Z0-9 _\-]+$', name):
        raise ValueError(f"Invalid indexer name: {name!r}")
    if not url or not _re.match(r'^https?://[a-zA-Z0-9._\-:/]+$', url) or len(url) > 500:
        raise ValueError(f"Invalid url: {url!r}")
    if not api_key or len(api_key) > 200 or not _re.match(r'^[a-zA-Z0-9]+$', api_key):
        raise ValueError("Invalid api_key (must be alnum, 1-200 chars)")
    if not _PROWLARR_DEF_RE.match(definition):
        raise ValueError(f"Invalid definition: {definition!r}")
    cats = categories if categories is not None else [5000]
    if not isinstance(cats, list) or not all(isinstance(c, int) and 0 < c < 10_000 for c in cats):
        raise ValueError("categories must be a list of ints in (0, 10000)")

    payload = {
        "name": name,
        "implementation": "Torznab",
        "implementationName": "Torznab",
        "configContract": "TorznabSettings",
        "definitionName": definition,
        "protocol": "torrent",
        "enable": True,
        "priority": 25,
        "fields": [
            {"name": "baseUrl", "value": url},
            {"name": "apiKey", "value": api_key},
            {"name": "categories", "value": cats},
        ],
    }
    c = _prowlarr()
    result = c.post("/indexer", json=payload)
    return {
        "id": result.get("id"),
        "name": result.get("name"),
        "implementation": result.get("implementation"),
        "enable": result.get("enable"),
    }


@mcp.tool()
def prowlarr_remove_indexer(indexer_id: int) -> dict:
    """Remove a Prowlarr indexer by numeric ID."""
    _audit("prowlarr_remove_indexer", {"indexer_id": indexer_id})
    _check_readonly("prowlarr_remove_indexer")
    if not isinstance(indexer_id, int) or indexer_id < 1 or indexer_id > 10_000:
        raise ValueError(f"Invalid indexer_id: {indexer_id!r}")
    c = _prowlarr()
    # Servarr DELETE returns 200/204 with empty body; reuse the underlying client.
    r = c._client.delete(f"{c.base}/api/{c.api_version}/indexer/{indexer_id}")
    r.raise_for_status()
    return {"id": indexer_id, "deleted": True}

