"""homelab-mcp-homeauto domain tools.

Generated by tools/phase_1_0_split_server.py from
mcp/src/homelab_mcp/server.py at the Phase 1.0 refactor. Tool source is
byte-faithful with the pre-split monolith. Edit the generator (and the
inventory) rather than hand-patching this file.
"""

from __future__ import annotations

# --- Imports (mirrors original server.py for tool body fidelity) ---
import os

import subprocess

from homelab_mcp.app import create_mcp

from homelab_mcp.audit import audit as _write_audit

from homelab_mcp.audit import configure_audit_logger

from homelab_mcp.clients import (
    ServarrClient,
    QbtClient,
    PlexClient,
    HomebridgeClient,
    Mylar3Client,
    get_sonarr_config,
    get_radarr_config,
    get_lidarr_config,
    get_readarr_config,
    get_mylar3_config,
    get_prowlarr_config,
    get_qbt_config,
    get_plex_config,
    get_homebridge_config,
    get_scrypted_config,
    get_dirigera_config,
    get_unifi_config,
    env,
)

from homelab_mcp.policy import WRITE_TOOLS as _POLICY_WRITE_TOOLS

from homelab_mcp.policy import check_readonly as _policy_check_readonly

from homelab_mcp.settings import (
    audit_log_path,
    cf_allowed_zones,
    cf_default_zone,
    env_flag,
    homelab_ingress_ip,
    ingress_host_re,
    require_env,
)

import json as _json

import re as _re

from datetime import datetime as _dt, timedelta as _td, timezone as _tz

import asyncio as _aio

import json as _json


# --- Shared runtime state: registers tools onto the singleton mcp instance ---
from homelab_mcp._runtime import (  # noqa: F401  imports used by tool bodies
    _AUDIT_LOG_PATH,
    _AUDIT_TOOL_RE,
    _DNS_NAME_RE,
    _DURATION_RE,
    _IMAGE_RE,
    _K8S_NAME_RE,
    _PROWLARR_DEF_RE,
    _READONLY,
    _WRITE_TOOLS,
    _apple_connect,
    _apple_devices_map,
    _apple_run,
    _audit,
    _audit_logger,
    _cf_get,
    _cf_token,
    _check_readonly,
    _client_summary,
    _clients,
    _dev_summary,
    _dirigera,
    _find_light,
    _flux,
    _homebridge,
    _kube,
    _lidarr,
    _mylar3,
    _need_dirigera,
    _plex,
    _prowlarr,
    _qbt,
    _radarr,
    _readarr,
    _resolve_mac,
    _sonarr,
    _ssh_exec,
    _unifi_run,
    _validate_duration,
    _validate_image,
    _validate_k8s_name,
    mcp,
)

# --- Domain tools (16) ---

@mcp.tool()
def homebridge_status() -> dict:
    """Get Homebridge status, version, and plugin update info."""
    c = _homebridge()
    hb = c.get("/status/homebridge")
    plugins = c.get("/plugins")
    updates = [p for p in plugins if p.get("updateAvailable")]
    return {
        "status": hb.get("status", "unknown"),
        "version": hb.get("homebridgeVersion", "unknown"),
        "plugins_installed": len(plugins),
        "plugins_update_available": len(updates),
        "updates": [{"name": p.get("name"), "installed": p.get("installedVersion"),
                      "latest": p.get("latestVersion")} for p in updates],
    }


@mcp.tool()
def homebridge_accessories() -> dict:
    """List all Homebridge accessories with their current status."""
    c = _homebridge()
    accessories = c.get("/accessories")
    return {
        "count": len(accessories),
        "accessories": [
            {"name": a.get("serviceName", a.get("accessoryInformation", {}).get("Name")),
             "type": a.get("type"),
             "uniqueId": a.get("uniqueId")}
            for a in accessories
        ],
    }


@mcp.tool()
def homebridge_plugins() -> dict:
    """List installed Homebridge plugins."""
    c = _homebridge()
    plugins = c.get("/plugins")
    return {
        "count": len(plugins),
        "plugins": [
            {"name": p.get("name"), "version": p.get("installedVersion"),
             "updateAvailable": p.get("updateAvailable", False)}
            for p in plugins
        ],
    }


@mcp.tool()
def scrypted_status() -> dict:
    """Check if Scrypted is reachable (health probe only)."""
    import httpx
    cfg = get_scrypted_config()
    try:
        r = httpx.get(cfg.url, timeout=10, follow_redirects=True)
        return {"reachable": r.status_code in (200, 301, 302),
                "http_code": r.status_code}
    except httpx.RequestError as e:
        return {"reachable": False, "error": str(e)}


@mcp.tool()
def dirigera_status() -> dict:
    """Check Dirigera hub reachability, device counts, and warnings (low battery, unreachable)."""
    h = _need_dirigera()
    counts = {}
    warnings = []
    for kind, fn in [
        ("lights", "get_lights"),
        ("outlets", "get_outlets"),
        ("blinds", "get_blinds"),
        ("controllers", "get_controllers"),
        ("environment_sensors", "get_environment_sensors"),
        ("motion_sensors", "get_motion_sensors"),
        ("open_close_sensors", "get_open_close_sensors"),
        ("air_purifiers", "get_air_purifiers"),
        ("scenes", "get_scenes"),
    ]:
        try:
            devices = getattr(h, fn)()
            counts[kind] = len(devices)
            # Check for unreachable devices and low battery
            if kind != "scenes":
                for d in devices:
                    name = getattr(getattr(d, "attributes", None), "custom_name", None) or getattr(d, "id", "?")
                    if getattr(d, "is_reachable", None) is False:
                        warnings.append({"device": name, "type": kind, "issue": "unreachable"})
                    batt = getattr(getattr(d, "attributes", None), "battery_percentage", None)
                    if batt is not None and batt < 20:
                        warnings.append({"device": name, "type": kind, "issue": f"low_battery ({batt}%)"})
        except Exception as e:
            counts[kind] = f"error: {e}"
    return {"reachable": True, "counts": counts, "warnings": warnings}


@mcp.tool()
def dirigera_devices(kind: str = "all") -> dict:
    """List Dirigera devices, optionally filtered by kind.
    kind ∈ {all, lights, outlets, blinds, controllers, environment_sensors,
            motion_sensors, open_close_sensors, air_purifiers}."""
    h = _need_dirigera()
    kinds = ["lights", "outlets", "blinds", "controllers", "environment_sensors",
             "motion_sensors", "open_close_sensors", "air_purifiers"] \
            if kind == "all" else [kind]
    out: dict = {}
    for k in kinds:
        fn = "get_" + k
        if not hasattr(h, fn):
            out[k] = {"error": f"unknown kind {k}"}
            continue
        try:
            out[k] = [_dev_summary(d) for d in getattr(h, fn)()]
        except Exception as e:
            out[k] = {"error": str(e)}
    return out


@mcp.tool()
def dirigera_lights() -> list[dict]:
    """List all lights with their on/off state, brightness, and color temp."""
    h = _need_dirigera()
    out = []
    for l in h.get_lights():
        a = l.attributes
        out.append({
            **_dev_summary(l),
            "is_on": getattr(a, "is_on", None),
            "light_level": getattr(a, "light_level", None),
            "color_temperature": getattr(a, "color_temperature", None),
            "color_hue": getattr(a, "color_hue", None),
            "color_saturation": getattr(a, "color_saturation", None),
        })
    return out


@mcp.tool()
def dirigera_outlets() -> list[dict]:
    """List smart outlets/plugs with on/off + power consumption when available."""
    h = _need_dirigera()
    out = []
    for o in h.get_outlets():
        a = o.attributes
        out.append({
            **_dev_summary(o),
            "is_on": getattr(a, "is_on", None),
            "current_active_power_w": getattr(a, "current_active_power", None),
            "total_energy_kwh": getattr(a, "total_energy_consumed", None),
        })
    return out


@mcp.tool()
def dirigera_sensors() -> dict:
    """All sensor readings: environment (temp/humidity/PM2.5/VOC/CO2),
    motion (detected + battery), open/close (state + battery)."""
    h = _need_dirigera()
    env_list = []
    for s in h.get_environment_sensors():
        a = s.attributes
        env_list.append({
            **_dev_summary(s),
            "temperature_c": getattr(a, "current_temperature", None),
            "humidity_pct": getattr(a, "current_r_h", None),
            "pm25": getattr(a, "current_p_m25", None),
            "co2_ppm": getattr(a, "current_c_o2", None),
            "voc_index": getattr(a, "voc_index", None),
        })
    motion = []
    for s in h.get_motion_sensors():
        a = s.attributes
        motion.append({
            **_dev_summary(s),
            "is_detected": getattr(a, "is_detected", None),
            "battery_pct": getattr(a, "battery_percentage", None),
            "light_level": getattr(a, "light_level", None),
        })
    oc = []
    for s in h.get_open_close_sensors():
        a = s.attributes
        oc.append({
            **_dev_summary(s),
            "is_open": getattr(a, "is_open", None),
            "battery_pct": getattr(a, "battery_percentage", None),
        })
    return {"environment": env_list, "motion": motion, "open_close": oc}


@mcp.tool()
def dirigera_blinds() -> list[dict]:
    """List blinds with current/target level and battery."""
    h = _need_dirigera()
    out = []
    for b in h.get_blinds():
        a = b.attributes
        out.append({
            **_dev_summary(b),
            "current_level": getattr(a, "blinds_current_level", None),
            "target_level": getattr(a, "blinds_target_level", None),
            "state": getattr(a, "blinds_state", None),
            "battery_pct": getattr(a, "battery_percentage", None),
        })
    return out


@mcp.tool()
def dirigera_scenes() -> list[dict]:
    """List all scenes (id, name, last triggered)."""
    h = _need_dirigera()
    out = []
    for s in h.get_scenes():
        out.append({
            "id": s.id,
            "name": getattr(getattr(s, "info", None), "name", None),
            "type": str(getattr(s, "type", "")),
            "last_triggered": str(getattr(s, "last_triggered", "")) or None,
        })
    return out


@mcp.tool()
def apple_scan(timeout: int = 5) -> list[dict]:
    """Scan the LAN for Apple TVs and HomePods. Returns identifiers + names
    + supported protocols. Use this BEFORE pairing to discover devices."""
    async def _scan():
        import pyatv
        loop = _aio.get_event_loop()
        results = await pyatv.scan(loop=loop, timeout=timeout)
        out = []
        for r in results:
            out.append({
                "name": r.name,
                "identifier": r.identifier,
                "address": str(r.address),
                "model": str(r.device_info.model) if r.device_info else None,
                "model_str": getattr(r.device_info, "raw_model", None) if r.device_info else None,
                "os": str(r.device_info.operating_system) if r.device_info else None,
                "protocols": sorted({str(s.protocol).split(".")[-1] for s in r.services}),
            })
        return out
    return _apple_run(_scan())


@mcp.tool()
def apple_devices() -> dict:
    """List configured Apple devices (from APPLE_TV_DEVICES env var)."""
    cfg = _apple_devices_map()
    return {
        name: {
            "identifier": v["identifier"],
            "paired_protocols": list(v.get("credentials", {}).keys()),
        }
        for name, v in cfg.items()
    }


@mcp.tool()
def apple_now_playing(device: str) -> dict:
    """What's playing on a configured Apple device."""
    async def _np():
        atv, _ = await _apple_connect(device)
        try:
            p = atv.metadata.playing if hasattr(atv.metadata, "playing") else await atv.metadata.playing()
            # pyatv 0.14+: metadata.playing is async
            if hasattr(p, "__await__"):
                p = await p
            return {
                "device": device,
                "title": getattr(p, "title", None),
                "artist": getattr(p, "artist", None),
                "album": getattr(p, "album", None),
                "app": getattr(getattr(atv, "apps", None), "app_list", lambda: None) and None,
                "device_state": str(getattr(p, "device_state", "")).split(".")[-1],
                "media_type": str(getattr(p, "media_type", "")).split(".")[-1],
                "position": getattr(p, "position", None),
                "total_time": getattr(p, "total_time", None),
            }
        finally:
            atv.close()
    return _apple_run(_np())


@mcp.tool()
def apple_apps(device: str) -> list[dict]:
    """List apps installed on the Apple TV (Companion protocol required)."""
    async def _apps():
        atv, _ = await _apple_connect(device)
        try:
            apps = await atv.apps.app_list()
            return [{"name": a.name, "identifier": a.identifier} for a in apps]
        finally:
            atv.close()
    return _apple_run(_apps())


@mcp.tool()
def homebridge_log_errors(tail: int = 200) -> list[dict]:
    """Parse Homebridge container logs for ERROR/WARN patterns with dedup."""
    try:
        raw = _kube("logs -l app=homebridge -n home-automation --tail=" + str(int(tail)))
        errors = {}
        for line in raw.split("\n"):
            if _re.search(r"ERROR|WARN|error|warn|fail", line, _re.IGNORECASE):
                key = line.strip()[:100]
                if key in errors:
                    errors[key]["count"] += 1
                else:
                    errors[key] = {"line": line.strip(), "count": 1}
        return sorted(errors.values(), key=lambda x: x["count"], reverse=True)[:30]
    except RuntimeError as e:
        return [{"error": str(e)}]

