"""homelab-mcp-media domain tools.

Generated by tools/phase_1_0_split_server.py from
mcp/src/homelab_mcp/server.py at the Phase 1.0 refactor. Tool source is
byte-faithful with the pre-split monolith. Edit the generator (and the
inventory) rather than hand-patching this file.
"""

from __future__ import annotations

# --- Imports (mirrors original server.py for tool body fidelity) ---
import os

import subprocess

from homelab_mcp.app import create_mcp

from homelab_mcp.audit import audit as _write_audit

from homelab_mcp.audit import configure_audit_logger

from homelab_mcp.clients import (
    ServarrClient,
    QbtClient,
    PlexClient,
    HomebridgeClient,
    Mylar3Client,
    get_sonarr_config,
    get_radarr_config,
    get_lidarr_config,
    get_readarr_config,
    get_mylar3_config,
    get_prowlarr_config,
    get_qbt_config,
    get_plex_config,
    get_homebridge_config,
    get_scrypted_config,
    get_dirigera_config,
    get_unifi_config,
    env,
)

from homelab_mcp.policy import WRITE_TOOLS as _POLICY_WRITE_TOOLS

from homelab_mcp.policy import check_readonly as _policy_check_readonly

from homelab_mcp.settings import (
    audit_log_path,
    cf_allowed_zones,
    cf_default_zone,
    env_flag,
    homelab_ingress_ip,
    ingress_host_re,
    require_env,
)

import json as _json

import re as _re

from datetime import datetime as _dt, timedelta as _td, timezone as _tz

import asyncio as _aio

import json as _json


# --- Shared runtime state: registers tools onto the singleton mcp instance ---
from homelab_mcp._runtime import (  # noqa: F401  imports used by tool bodies
    _AUDIT_LOG_PATH,
    _AUDIT_TOOL_RE,
    _DNS_NAME_RE,
    _DURATION_RE,
    _IMAGE_RE,
    _K8S_NAME_RE,
    _PROWLARR_DEF_RE,
    _READONLY,
    _WRITE_TOOLS,
    _apple_connect,
    _apple_devices_map,
    _apple_run,
    _audit,
    _audit_logger,
    _cf_get,
    _cf_token,
    _check_readonly,
    _client_summary,
    _clients,
    _dev_summary,
    _dirigera,
    _find_light,
    _flux,
    _homebridge,
    _kube,
    _lidarr,
    _mylar3,
    _need_dirigera,
    _plex,
    _prowlarr,
    _qbt,
    _radarr,
    _readarr,
    _resolve_mac,
    _sonarr,
    _ssh_exec,
    _unifi_run,
    _validate_duration,
    _validate_image,
    _validate_k8s_name,
    mcp,
)

# --- Domain tools (30) ---

@mcp.tool()
def sonarr_health() -> dict:
    """Check Sonarr health status, version, and disk space."""
    c = _sonarr()
    health = c.get("/health")
    status = c.get("/system/status")
    disk = c.get("/diskspace")
    return {
        "version": status.get("version", "unknown"),
        "health_issues": len(health),
        "health": health,
        "diskspace": disk,
    }


@mcp.tool()
def sonarr_missing(page_size: int = 50) -> dict:
    """List missing episodes from Sonarr."""
    c = _sonarr()
    data = c.get("/wanted/missing", pageSize=page_size, sortKey="airDateUtc",
                 sortDirection="descending", includeSeries="true")
    return {
        "total_missing": data["totalRecords"],
        "episodes": [
            {"series": r["series"]["title"], "season": r["seasonNumber"],
             "episode": r["episodeNumber"], "title": r["title"],
             "airDate": r.get("airDateUtc")}
            for r in data.get("records", [])
        ],
    }


@mcp.tool()
def sonarr_queue() -> dict:
    """Show Sonarr download queue with progress and errors."""
    c = _sonarr()
    data = c.get("/queue", pageSize=50, includeSeries="true", includeEpisode="true")
    return {
        "total_queued": data["totalRecords"],
        "items": [
            {"title": r.get("title"), "status": r.get("status"),
             "size": r.get("size"), "sizeleft": r.get("sizeleft"),
             "series": r.get("series", {}).get("title"),
             "episode": r.get("episode", {}).get("title"),
             "error": r.get("errorMessage")}
            for r in data.get("records", [])
        ],
    }


@mcp.tool()
def sonarr_calendar(days: int = 7) -> dict:
    """Get upcoming episodes from Sonarr for the next N days."""
    from datetime import datetime, timedelta, timezone
    now = datetime.now(timezone.utc)
    start = now.strftime("%Y-%m-%dT00:00:00Z")
    end = (now + timedelta(days=days)).strftime("%Y-%m-%dT00:00:00Z")
    c = _sonarr()
    data = c.get("/calendar", start=start, end=end, includeSeries="true")
    return {
        "upcoming_count": len(data),
        "episodes": [
            {"series": ep.get("series", {}).get("title"),
             "season": ep.get("seasonNumber"), "episode": ep.get("episodeNumber"),
             "title": ep.get("title"), "airDate": ep.get("airDateUtc"),
             "hasFile": ep.get("hasFile")}
            for ep in data
        ],
    }


@mcp.tool()
def sonarr_series() -> dict:
    """List all TV series in Sonarr with monitoring status."""
    c = _sonarr()
    series = c.get("/series")
    return {
        "count": len(series),
        "series": [
            {"title": s["title"], "year": s.get("year"),
             "monitored": s["monitored"], "status": s.get("status"),
             "episodeCount": s.get("statistics", {}).get("episodeCount", 0),
             "episodeFileCount": s.get("statistics", {}).get("episodeFileCount", 0),
             "sizeOnDisk": s.get("statistics", {}).get("sizeOnDisk", 0)}
            for s in series
        ],
    }


@mcp.tool()
def radarr_health() -> dict:
    """Check Radarr health status, version, and disk space."""
    c = _radarr()
    health = c.get("/health")
    status = c.get("/system/status")
    disk = c.get("/diskspace")
    return {
        "version": status.get("version", "unknown"),
        "health_issues": len(health),
        "health": health,
        "diskspace": disk,
    }


@mcp.tool()
def radarr_missing(page_size: int = 50) -> dict:
    """List movies missing files in Radarr."""
    c = _radarr()
    data = c.get("/wanted/missing", pageSize=page_size)
    return {
        "total_missing": data["totalRecords"],
        "movies": [
            {"title": r["title"], "year": r.get("year"),
             "monitored": r["monitored"]}
            for r in data.get("records", [])
        ],
    }


@mcp.tool()
def radarr_queue() -> dict:
    """Show Radarr download queue."""
    c = _radarr()
    data = c.get("/queue", pageSize=50)
    return {
        "total_queued": data["totalRecords"],
        "items": [
            {"title": r.get("title"), "status": r.get("status"),
             "size": r.get("size"), "sizeleft": r.get("sizeleft"),
             "error": r.get("errorMessage")}
            for r in data.get("records", [])
        ],
    }


@mcp.tool()
def radarr_movies() -> dict:
    """List all movies in Radarr with file status."""
    c = _radarr()
    movies = c.get("/movie")
    return {
        "count": len(movies),
        "movies": [
            {"title": m["title"], "year": m.get("year"),
             "monitored": m["monitored"], "hasFile": m.get("hasFile"),
             "sizeOnDisk": m.get("sizeOnDisk", 0)}
            for m in movies
        ],
    }


@mcp.tool()
def radarr_calendar(days: int = 30) -> dict:
    """Get upcoming movie releases from Radarr."""
    from datetime import datetime, timedelta, timezone
    now = datetime.now(timezone.utc)
    start = now.strftime("%Y-%m-%dT00:00:00Z")
    end = (now + timedelta(days=days)).strftime("%Y-%m-%dT00:00:00Z")
    c = _radarr()
    data = c.get("/calendar", start=start, end=end)
    return {
        "upcoming_count": len(data),
        "movies": [
            {"title": m.get("title"), "year": m.get("year"),
             "releaseDate": m.get("digitalRelease") or m.get("physicalRelease")}
            for m in data
        ],
    }


@mcp.tool()
def lidarr_health() -> dict:
    """Check Lidarr health status, version, and disk space."""
    c = _lidarr()
    health = c.get("/health")
    status = c.get("/system/status")
    disk = c.get("/diskspace")
    return {
        "version": status.get("version", "unknown"),
        "health_issues": len(health),
        "health": health,
        "diskspace": disk,
    }


@mcp.tool()
def lidarr_missing(page_size: int = 50) -> dict:
    """List missing albums from Lidarr (monitored artists with no file)."""
    c = _lidarr()
    data = c.get("/wanted/missing", pageSize=page_size, sortKey="releaseDate",
                 sortDirection="descending", includeArtist="true")
    return {
        "total_missing": data["totalRecords"],
        "albums": [
            {"artist": r.get("artist", {}).get("artistName"),
             "title": r.get("title"),
             "releaseDate": r.get("releaseDate"),
             "monitored": r.get("monitored")}
            for r in data.get("records", [])
        ],
    }


@mcp.tool()
def readarr_health() -> dict:
    """Check Readarr health status, version, and disk space."""
    c = _readarr()
    health = c.get("/health")
    status = c.get("/system/status")
    disk = c.get("/diskspace")
    return {
        "version": status.get("version", "unknown"),
        "health_issues": len(health),
        "health": health,
        "diskspace": disk,
    }


@mcp.tool()
def readarr_missing(page_size: int = 50) -> dict:
    """List missing books from Readarr (monitored authors with no file)."""
    c = _readarr()
    data = c.get("/wanted/missing", pageSize=page_size, sortKey="releaseDate",
                 sortDirection="descending", includeAuthor="true")
    return {
        "total_missing": data["totalRecords"],
        "books": [
            {"author": r.get("author", {}).get("authorName"),
             "title": r.get("title"),
             "releaseDate": r.get("releaseDate"),
             "monitored": r.get("monitored")}
            for r in data.get("records", [])
        ],
    }


@mcp.tool()
def mylar3_health() -> dict:
    """Check Mylar3 version and update status."""
    c = _mylar3()
    res = c.call("getVersion")
    data = res.get("data", {}) if isinstance(res, dict) else {}
    return {
        "current_version": data.get("current_version"),
        "latest_version": data.get("latest_version"),
        "commits_behind": data.get("commits_behind"),
        "install_type": data.get("install_type"),
    }


@mcp.tool()
def mylar3_series() -> dict:
    """List all comic series tracked by Mylar3 (the library index)."""
    c = _mylar3()
    res = c.call("getIndex")
    series = res.get("data", []) if isinstance(res, dict) else []
    return {
        "total_series": len(series),
        "series": [
            {"name": s.get("name") or s.get("ComicName"),
             "year": s.get("year") or s.get("ComicYear"),
             "publisher": s.get("publisher") or s.get("ComicPublisher"),
             "status": s.get("status") or s.get("Status"),
             "have": s.get("have") or s.get("Have"),
             "total": s.get("total") or s.get("Total")}
            for s in series
        ],
    }


@mcp.tool()
def mylar3_missing() -> dict:
    """List wanted (missing) comic issues across all monitored series."""
    c = _mylar3()
    res = c.call("getWanted")
    issues = res.get("issues", []) if isinstance(res, dict) else (res if isinstance(res, list) else [])
    return {
        "total_missing": len(issues),
        "issues": [
            {"series": i.get("ComicName"),
             "issue": i.get("Issue_Number"),
             "year": i.get("IssueYear"),
             "status": i.get("Status")}
            for i in issues
        ],
    }


@mcp.tool()
def prowlarr_health() -> dict:
    """Check Prowlarr health status, version, and indexer counts."""
    c = _prowlarr()
    health = c.get("/health")
    status = c.get("/system/status")
    indexers = c.get("/indexer")
    enabled = [i for i in indexers if i.get("enable")]
    return {
        "version": status.get("version", "unknown"),
        "health_issues": len(health),
        "health": health,
        "indexers_total": len(indexers),
        "indexers_enabled": len(enabled),
    }


@mcp.tool()
def prowlarr_test_indexers() -> dict:
    """Test all configured indexers in Prowlarr."""
    c = _prowlarr()
    c.post("/indexer/testall")
    indexers = c.get("/indexer")
    return {
        "tested": len(indexers),
        "indexers": [
            {"name": i["name"], "enabled": i.get("enable"),
             "protocol": i.get("protocol")}
            for i in indexers
        ],
    }


@mcp.tool()
def prowlarr_search(query: str) -> dict:
    """Search across all Prowlarr indexers."""
    c = _prowlarr()
    results = c.get("/search", query=query)
    return {
        "result_count": len(results),
        "results": [
            {"title": r.get("title"), "indexer": r.get("indexer"),
             "size": r.get("size"), "seeders": r.get("seeders")}
            for r in results[:20]
        ],
    }


@mcp.tool()
def qbt_status() -> dict:
    """Get qBittorrent transfer info and torrent summary counts."""
    c = _qbt()
    transfer = c.get("/transfer/info")
    torrents = c.get("/torrents/info")
    states = {}
    for t in torrents:
        s = t.get("state", "unknown")
        states[s] = states.get(s, 0) + 1
    return {
        "dl_speed_bytes": transfer.get("dl_info_speed", 0),
        "ul_speed_bytes": transfer.get("up_info_speed", 0),
        "connection": transfer.get("connection_status", "unknown"),
        "torrents_total": len(torrents),
        "by_state": states,
    }


@mcp.tool()
def qbt_torrents(filter: str = "all") -> dict:
    """List qBittorrent torrents. Filter: all|downloading|seeding|completed|paused|active|stalled|errored."""
    c = _qbt()
    data = c.get("/torrents/info", filter=filter)
    return {
        "filter": filter,
        "count": len(data),
        "torrents": [
            {"name": t["name"], "state": t["state"], "progress": t["progress"],
             "size": t["size"], "dlspeed": t["dlspeed"], "upspeed": t["upspeed"],
             "ratio": t["ratio"], "category": t.get("category", ""),
             "tags": t.get("tags", "")}
            for t in data[:50]
        ],
    }


@mcp.tool()
def plex_status() -> dict:
    """Get Plex server identity and active streaming sessions."""
    c = _plex()
    identity = c.get("/")
    mc = identity.get("MediaContainer", {})
    sessions = c.get("/status/sessions")
    sc = sessions.get("MediaContainer", {})
    return {
        "server_name": mc.get("friendlyName", "unknown"),
        "version": mc.get("version", "unknown"),
        "platform": mc.get("platform", "unknown"),
        "active_sessions": sc.get("size", 0),
        "streams": [
            {"user": s.get("User", {}).get("title"),
             "title": s.get("title"),
             "type": s.get("type"),
             "player": s.get("Player", {}).get("title"),
             "state": s.get("Player", {}).get("state")}
            for s in sc.get("Metadata", [])
        ],
    }


@mcp.tool()
def plex_libraries() -> dict:
    """List all Plex libraries with type and refresh status."""
    c = _plex()
    data = c.get("/library/sections")
    mc = data.get("MediaContainer", {})
    return {
        "library_count": mc.get("size", 0),
        "libraries": [
            {"key": lib["key"], "title": lib["title"], "type": lib["type"],
             "refreshing": lib.get("refreshing", False)}
            for lib in mc.get("Directory", [])
        ],
    }


@mcp.tool()
def plex_recent(count: int = 20) -> dict:
    """Get recently added media from Plex."""
    c = _plex()
    data = c.get("/library/recentlyAdded")
    mc = data.get("MediaContainer", {})
    items = mc.get("Metadata", [])[:count]
    return {
        "total_recent": mc.get("size", 0),
        "items": [
            {"title": i.get("title"), "type": i.get("type"),
             "year": i.get("year"), "addedAt": i.get("addedAt"),
             "parentTitle": i.get("parentTitle"),
             "grandparentTitle": i.get("grandparentTitle")}
            for i in items
        ],
    }


@mcp.tool()
def media_pipeline_health() -> dict:
    """One-call health check of the entire media pipeline: Sonarr, Radarr, Prowlarr, qBittorrent, Plex."""
    results = {}
    for name, fn in [("sonarr", sonarr_health), ("radarr", radarr_health),
                     ("prowlarr", prowlarr_health), ("qbittorrent", qbt_status),
                     ("plex", plex_status)]:
        try:
            data = fn()
            results[name] = {"ok": True, "data": data}
        except Exception as e:
            results[name] = {"ok": False, "error": str(e)}
    all_ok = all(r.get("ok") for r in results.values())
    return {"all_ok": all_ok, "services": results}


@mcp.tool()
def media_disk_pressure() -> dict:
    """Cross-check disk usage from host, Sonarr, and Radarr disk space APIs."""
    result = {}
    try:
        result["host_disk"] = host_disk()
    except Exception as e:
        result["host_disk"] = {"error": str(e)}
    try:
        result["sonarr_disk"] = _sonarr().get("/diskspace")
    except Exception as e:
        result["sonarr_disk"] = {"error": str(e)}
    try:
        result["radarr_disk"] = _radarr().get("/diskspace")
    except Exception as e:
        result["radarr_disk"] = {"error": str(e)}
    return result


@mcp.tool()
def media_indexer_health() -> dict:
    """Test all Prowlarr indexers and report health."""
    try:
        return prowlarr_test_indexers()
    except Exception as e:
        return {"ok": False, "error": str(e)}


@mcp.tool()
def cf_dns_list(zone: str = "") -> dict:
    """List all DNS records in a Cloudflare zone (read-only).

    ``zone`` defaults to ``CF_DEFAULT_ZONE`` (or first entry of
    ``CF_ALLOWED_ZONES`` if unset). The resolved zone MUST be in
    ``CF_ALLOWED_ZONES``.
    """
    allowed = cf_allowed_zones()
    zone = (zone or cf_default_zone()).strip().lower()
    if zone not in allowed:
        raise ValueError(
            f"Zone {zone!r} not allowed. Allowed: {sorted(allowed)}"
        )
    zones = _cf_get("/zones", name=zone).get("result", [])
    if not zones:
        return {"zone": zone, "found": False, "records": []}
    zone_id = zones[0]["id"]
    records = _cf_get(f"/zones/{zone_id}/dns_records", per_page=200).get("result", [])
    return {
        "zone": zone,
        "zone_id": zone_id,
        "found": True,
        "count": len(records),
        "records": [
            {"name": r.get("name"), "type": r.get("type"),
             "content": r.get("content"), "ttl": r.get("ttl"),
             "proxied": r.get("proxied"), "comment": r.get("comment")}
            for r in records
        ],
    }


@mcp.tool()
def cf_dns_get(name: str, zone: str = "") -> dict:
    """Look up a single DNS record by name in a Cloudflare zone (read-only)."""
    allowed = cf_allowed_zones()
    zone = (zone or cf_default_zone()).strip().lower()
    if zone not in allowed:
        raise ValueError(
            f"Zone {zone!r} not allowed. Allowed: {sorted(allowed)}"
        )
    if not name or len(name) > 253 or not _DNS_NAME_RE.match(name):
        raise ValueError(f"Invalid DNS name: {name!r}")
    zones = _cf_get("/zones", name=zone).get("result", [])
    if not zones:
        return {"name": name, "found": False}
    zone_id = zones[0]["id"]
    records = _cf_get(f"/zones/{zone_id}/dns_records", name=name).get("result", [])
    return {
        "name": name,
        "zone": zone,
        "found": bool(records),
        "records": [
            {"id": r.get("id"), "type": r.get("type"), "content": r.get("content"),
             "ttl": r.get("ttl"), "proxied": r.get("proxied"),
             "comment": r.get("comment")}
            for r in records
        ],
    }

