"""homelab-mcp-network domain tools.

Generated by tools/phase_1_0_split_server.py from
mcp/src/homelab_mcp/server.py at the Phase 1.0 refactor. Tool source is
byte-faithful with the pre-split monolith. Edit the generator (and the
inventory) rather than hand-patching this file.
"""

from __future__ import annotations

# --- Imports (mirrors original server.py for tool body fidelity) ---
import os

import subprocess

from homelab_mcp.app import create_mcp

from homelab_mcp.audit import audit as _write_audit

from homelab_mcp.audit import configure_audit_logger

from homelab_mcp.clients import (
    ServarrClient,
    QbtClient,
    PlexClient,
    HomebridgeClient,
    Mylar3Client,
    get_sonarr_config,
    get_radarr_config,
    get_lidarr_config,
    get_readarr_config,
    get_mylar3_config,
    get_prowlarr_config,
    get_qbt_config,
    get_plex_config,
    get_homebridge_config,
    get_scrypted_config,
    get_dirigera_config,
    get_unifi_config,
    env,
)

from homelab_mcp.policy import WRITE_TOOLS as _POLICY_WRITE_TOOLS

from homelab_mcp.policy import check_readonly as _policy_check_readonly

from homelab_mcp.settings import (
    audit_log_path,
    cf_allowed_zones,
    cf_default_zone,
    env_flag,
    homelab_ingress_ip,
    ingress_host_re,
    require_env,
)

import json as _json

import re as _re

from datetime import datetime as _dt, timedelta as _td, timezone as _tz

import asyncio as _aio

import json as _json


# --- Shared runtime state: registers tools onto the singleton mcp instance ---
from homelab_mcp._runtime import (  # noqa: F401  imports used by tool bodies
    _AUDIT_LOG_PATH,
    _AUDIT_TOOL_RE,
    _DNS_NAME_RE,
    _DURATION_RE,
    _IMAGE_RE,
    _K8S_NAME_RE,
    _PROWLARR_DEF_RE,
    _READONLY,
    _WRITE_TOOLS,
    _apple_connect,
    _apple_devices_map,
    _apple_run,
    _audit,
    _audit_logger,
    _cf_get,
    _cf_token,
    _check_readonly,
    _client_summary,
    _clients,
    _dev_summary,
    _dirigera,
    _find_light,
    _flux,
    _homebridge,
    _kube,
    _lidarr,
    _mylar3,
    _need_dirigera,
    _plex,
    _prowlarr,
    _qbt,
    _radarr,
    _readarr,
    _resolve_mac,
    _sonarr,
    _ssh_exec,
    _unifi_run,
    _validate_duration,
    _validate_image,
    _validate_k8s_name,
    mcp,
)

# --- Domain tools (7) ---

@mcp.tool()
def unifi_health() -> dict:
    """UniFi controller info: version, uptime, hostname, alarms, update available."""
    async def _h(controller):
        await controller.system_information.update()
        info = next(iter(controller.system_information.values()), None)
        if info is None:
            return {"ok": False, "error": "no system_information returned"}
        return {
            "ok": True,
            "name":             info.name,
            "hostname":         info.hostname,
            "version":          info.version,
            "previous_version": info.previous_version,
            "update_available": info.update_available,
            "device_type":      info.device_type,
            "uptime_seconds":   info.uptime,
            "external_ip":      info.ip_address,
        }
    return _unifi_run(_h)


@mcp.tool()
def unifi_clients(active_only: bool = True, top: int = 50) -> list[dict]:
    """List UniFi clients. active_only=True returns currently-connected only.
    Sorted by last_seen desc; truncated to `top`."""
    async def _c(controller):
        await controller.clients.update()
        if not active_only:
            await controller.clients_all.update()
            items = list(controller.clients_all.values())
        else:
            items = list(controller.clients.values())
        items.sort(key=lambda x: getattr(x, "last_seen", 0), reverse=True)
        return [_client_summary(c) for c in items[:top]]
    return _unifi_run(_c)


@mcp.tool()
def unifi_client(name_or_mac: str) -> dict:
    """Detail on a single client by MAC, hostname, or display name."""
    async def _c(controller):
        await controller.clients.update()
        await controller.clients_all.update()
        mac = _resolve_mac(controller, name_or_mac).lower()
        c = controller.clients.get(mac) or controller.clients_all.get(mac)
        if c is None:
            raise RuntimeError(f"client {mac} not found after lookup")
        return _client_summary(c)
    return _unifi_run(_c)


@mcp.tool()
def unifi_devices() -> list[dict]:
    """List UniFi network hardware (UAPs, switches, gateways)."""
    async def _d(controller):
        await controller.devices.update()
        out = []
        for d in controller.devices.values():
            out.append({
                "mac":        d.mac,
                "name":       d.raw.get("name", ""),
                "model":      d.raw.get("model", ""),
                "type":       d.raw.get("type", ""),
                "ip":         d.raw.get("ip", ""),
                "version":    d.raw.get("version", ""),
                "uptime":     d.raw.get("uptime", 0),
                "state":      d.raw.get("state", None),
                "num_clients": d.raw.get("num_sta", 0),
            })
        return out
    return _unifi_run(_d)


@mcp.tool()
def unifi_wlans() -> list[dict]:
    """List configured WLAN/SSIDs."""
    async def _w(controller):
        await controller.wlans.update()
        out = []
        for w in controller.wlans.values():
            out.append({
                "id":       w.id,
                "name":     w.name,
                "enabled":  w.enabled,
                "is_guest": getattr(w, "is_guest", False),
                "security": getattr(w, "security", ""),
                "vlan":     getattr(w, "vlan", None),
                "passphrase": getattr(w, "x_passphrase", "") or "",
            })
        return out
    return _unifi_run(_w)


@mcp.tool()
def unifi_port_forwards() -> list[dict]:
    """List port forwarding rules."""
    async def _pf(controller):
        await controller.port_forwarding.update()
        out = []
        for r in controller.port_forwarding.values():
            out.append({
                "id":         r.id,
                "name":       r.raw.get("name", ""),
                "enabled":    r.raw.get("enabled", False),
                "src":        r.raw.get("src", ""),
                "dst_port":   r.raw.get("dst_port", ""),
                "fwd_ip":     r.raw.get("fwd", ""),
                "fwd_port":   r.raw.get("fwd_port", ""),
                "protocol":   r.raw.get("proto", ""),
            })
        return out
    return _unifi_run(_pf)


@mcp.tool()
def unifi_top_talkers(top: int = 10) -> list[dict]:
    """Top bandwidth users right now (by current rx+tx rate, kbps)."""
    async def _t(controller):
        await controller.clients.update()
        items = list(controller.clients.values())
        def total(c):
            return (getattr(c, "rx_rate", 0) or 0) + (getattr(c, "tx_rate", 0) or 0)
        items.sort(key=total, reverse=True)
        out = []
        for c in items[:top]:
            out.append({
                "name":   c.name or c.hostname or c.mac,
                "mac":    c.mac,
                "ip":     c.ip,
                "rx_kbps": getattr(c, "rx_rate", 0),
                "tx_kbps": getattr(c, "tx_rate", 0),
                "total_kbps": total(c),
                "essid":  c.essid,
            })
        return out
    return _unifi_run(_t)

