"""homelab-mcp-platform domain tools.

Generated by tools/phase_1_0_split_server.py from
mcp/src/homelab_mcp/server.py at the Phase 1.0 refactor. Tool source is
byte-faithful with the pre-split monolith. Edit the generator (and the
inventory) rather than hand-patching this file.
"""

from __future__ import annotations

# --- Imports (mirrors original server.py for tool body fidelity) ---
import os

import subprocess

from homelab_mcp.app import create_mcp

from homelab_mcp.audit import audit as _write_audit

from homelab_mcp.audit import configure_audit_logger

from homelab_mcp.clients import (
    ServarrClient,
    QbtClient,
    PlexClient,
    HomebridgeClient,
    Mylar3Client,
    get_sonarr_config,
    get_radarr_config,
    get_lidarr_config,
    get_readarr_config,
    get_mylar3_config,
    get_prowlarr_config,
    get_qbt_config,
    get_plex_config,
    get_homebridge_config,
    get_scrypted_config,
    get_dirigera_config,
    get_unifi_config,
    env,
)

from homelab_mcp.policy import WRITE_TOOLS as _POLICY_WRITE_TOOLS

from homelab_mcp.policy import check_readonly as _policy_check_readonly

from homelab_mcp.settings import (
    audit_log_path,
    cf_allowed_zones,
    cf_default_zone,
    env_flag,
    homelab_ingress_ip,
    ingress_host_re,
    require_env,
)

import json as _json

import re as _re

from datetime import datetime as _dt, timedelta as _td, timezone as _tz

import asyncio as _aio

import json as _json


# --- Shared runtime state: registers tools onto the singleton mcp instance ---
from homelab_mcp._runtime import (  # noqa: F401  imports used by tool bodies
    _AUDIT_LOG_PATH,
    _AUDIT_TOOL_RE,
    _DNS_NAME_RE,
    _DURATION_RE,
    _IMAGE_RE,
    _K8S_NAME_RE,
    _PROWLARR_DEF_RE,
    _READONLY,
    _WRITE_TOOLS,
    _apple_connect,
    _apple_devices_map,
    _apple_run,
    _audit,
    _audit_logger,
    _cf_get,
    _cf_token,
    _check_readonly,
    _client_summary,
    _clients,
    _dev_summary,
    _dirigera,
    _find_light,
    _flux,
    _homebridge,
    _kube,
    _lidarr,
    _mylar3,
    _need_dirigera,
    _plex,
    _prowlarr,
    _qbt,
    _radarr,
    _readarr,
    _resolve_mac,
    _sonarr,
    _ssh_exec,
    _unifi_run,
    _validate_duration,
    _validate_image,
    _validate_k8s_name,
    mcp,
)

# --- Domain tools (51) ---

@mcp.tool()
def host_status() -> dict:
    """Get Ubuntu host system status: uptime, load, disk, memory, k3s, packages, reboot status, OS version."""
    cmd = (
        "echo UPTIME:$(uptime -s); "
        "echo LOAD:$(cat /proc/loadavg | cut -d' ' -f1-3); "
        "echo DISK:$(df -h / /media/nas 2>/dev/null | tail -n+2 | awk '{print $1,$2,$3,$4,$5,$6}' | paste -sd'|'); "
        "echo MEM:$(free -m | awk '/^Mem:/{print $2,$3,$4}'); "
        "echo K3S:$(systemctl is-active k3s 2>/dev/null || echo unknown); "
        "echo UPDATES:$(apt list --upgradable 2>/dev/null | grep -c upgradable || echo 0); "
        "echo REBOOT:$(test -f /var/run/reboot-required && echo yes || echo no); "
        "echo OS:$(lsb_release -ds 2>/dev/null); "
        "echo KERNEL:$(uname -r)"
    )
    output = _ssh_exec(cmd)
    parsed = {}
    for line in output.split("\n"):
        if ":" in line:
            key, _, val = line.partition(":")
            parsed[key.strip()] = val.strip()

    mem_parts = parsed.get("MEM", "0 0 0").split()
    return {
        "uptime_since": parsed.get("UPTIME", ""),
        "load_avg": parsed.get("LOAD", ""),
        "disk": parsed.get("DISK", ""),
        "memory_mb": {"total": int(mem_parts[0]) if mem_parts else 0,
                       "used": int(mem_parts[1]) if len(mem_parts) > 1 else 0},
        "k3s_status": parsed.get("K3S", "unknown"),
        "packages_upgradable": int(parsed.get("UPDATES", "0") or "0"),
        "reboot_required": parsed.get("REBOOT", "no") == "yes",
        "os_version": parsed.get("OS", ""),
        "kernel": parsed.get("KERNEL", ""),
    }


@mcp.tool()
def host_disk() -> dict:
    """Get disk usage for all mount points on the Ubuntu host."""
    output = _ssh_exec("df -h | tail -n+2")
    mounts = []
    for line in output.split("\n"):
        parts = line.split()
        if len(parts) >= 6:
            mounts.append({
                "filesystem": parts[0], "size": parts[1], "used": parts[2],
                "available": parts[3], "use_pct": parts[4], "mount": parts[5],
            })
    return {"mounts": mounts}


@mcp.tool()
def host_services() -> dict:
    """Check status of key services on the Ubuntu host."""
    services = ["k3s", "ssh", "docker", "containerd"]
    output = _ssh_exec(
        " ; ".join(f'echo "{s}:$(systemctl is-active {s} 2>/dev/null || echo unknown)"'
                    for s in services)
    )
    result = {}
    for line in output.split("\n"):
        if ":" in line:
            name, _, status = line.partition(":")
            result[name.strip()] = status.strip()
    return {"services": result}


@mcp.tool()
def host_packages_upgradable() -> dict:
    """List upgradable packages on the Ubuntu host."""
    output = _ssh_exec("apt list --upgradable 2>/dev/null | tail -n+2")
    packages = []
    for line in output.split("\n"):
        if line.strip():
            parts = line.split("/")
            packages.append(parts[0] if parts else line.strip())
    return {"count": len(packages), "packages": packages[:50]}


@mcp.tool()
def host_journal(unit: str, lines: int = 200) -> str:
    """Read systemd journal for a unit (e.g., 'microk8s.daemon-kubelite', 'restic-backup')."""
    _validate_k8s_name(unit, "unit")  # reuse — same character class
    return _ssh_exec(f"journalctl -u {unit} --no-pager -n {int(lines)}")


@mcp.tool()
def host_failed_units() -> list[str]:
    """List failed systemd units on the host."""
    raw = _ssh_exec("systemctl --failed --no-legend --no-pager")
    return [line.strip() for line in raw.split("\n") if line.strip()]


@mcp.tool()
def host_security_audit() -> dict:
    """Quick security posture check: UFW, unattended-upgrades, last login, last reboot."""
    ufw = _ssh_exec("sudo ufw status 2>/dev/null || echo 'ufw not installed'")
    ua = _ssh_exec("dpkg -l unattended-upgrades 2>/dev/null | grep -q ^ii && echo 'installed' || echo 'not installed'")
    last_login = _ssh_exec("last -n 5 --time-format iso 2>/dev/null || last -n 5")
    last_reboot = _ssh_exec("who -b 2>/dev/null || uptime -s")
    return {
        "ufw": ufw,
        "unattended_upgrades": ua,
        "last_logins": last_login,
        "last_reboot": last_reboot,
    }


@mcp.tool()
def host_smart() -> dict:
    """SMART disk health summary for each disk on the host."""
    try:
        raw = _ssh_exec("sudo smartctl --scan 2>/dev/null | awk '{print $1}'")
        disks = {}
        for disk in raw.split("\n"):
            disk = disk.strip()
            if disk:
                info = _ssh_exec(f"sudo smartctl -H {disk} 2>/dev/null | grep -i 'overall\\|result'")
                disks[disk] = info.strip()
        return {"disks": disks}
    except Exception as e:
        return {"error": str(e)}


@mcp.tool()
def host_nfs_status() -> dict:
    """Check NFS mount status and reachability."""
    mounts = _ssh_exec("mount | grep nfs || echo 'no NFS mounts'")
    return {"nfs_mounts": mounts}


@mcp.tool()
def gitops_drift() -> dict:
    """Compare cluster state vs last applied Flux revision for each kustomization."""
    try:
        raw = _ssh_exec("flux get kustomizations -A 2>&1")
        return {"drift_report": raw}
    except Exception as e:
        return {"error": str(e)}


@mcp.tool()
def gitops_app_inventory() -> list[dict]:
    """Walk apps/**/kustomization.yaml and return registered apps with image + namespace."""
    try:
        raw = _ssh_exec(
            "cd ~/src/homelab && "
            "find apps -name kustomization.yaml -exec grep -l 'resources' {} \\; | sort"
        )
        apps = []
        for path in raw.split("\n"):
            path = path.strip()
            if not path:
                continue
            parts = path.split("/")
            if len(parts) >= 3:
                apps.append({
                    "category": parts[1],
                    "name": parts[2],
                    "path": path,
                })
        return apps
    except Exception as e:
        return [{"error": str(e)}]


@mcp.tool()
def gitops_secret_audit() -> list[dict]:
    """Find any Secret manifests with literal data blocks (potential plaintext leak)."""
    try:
        raw = _ssh_exec(
            "cd ~/src/homelab && "
            "grep -rl 'kind: Secret' apps/ clusters/ 2>/dev/null | "
            "xargs -I{} grep -l '^data:' {} 2>/dev/null || echo ''"
        )
        files = [f.strip() for f in raw.split("\n") if f.strip()]
        return [{"file": f, "warning": "Contains literal data: block — verify it's SOPS-encrypted"} for f in files]
    except Exception as e:
        return [{"error": str(e)}]


@mcp.tool()
def kube_pods(ns: str = "", failing_only: bool = False) -> list[dict]:
    """List Kubernetes pods. Optionally filter to a namespace or only non-Running/Completed pods."""
    if ns:
        _validate_k8s_name(ns, "namespace")
    ns_flag = f"-n {ns}" if ns else "--all-namespaces"
    raw = _kube(f"get pods {ns_flag} -o json")
    data = _json.loads(raw)
    pods = []
    for item in data.get("items", []):
        meta = item.get("metadata", {})
        status = item.get("status", {})
        phase = status.get("phase", "Unknown")
        restart_count = sum(
            cs.get("restartCount", 0)
            for cs in status.get("containerStatuses", [])
        )
        pod = {
            "name": meta.get("name"),
            "namespace": meta.get("namespace"),
            "phase": phase,
            "restarts": restart_count,
            "node": item.get("spec", {}).get("nodeName"),
        }
        if failing_only and phase in ("Running", "Succeeded"):
            continue
        pods.append(pod)
    return pods


@mcp.tool()
def kube_describe(name: str, ns: str = "default") -> str:
    """Describe a Kubernetes pod (events, conditions, volume status)."""
    _validate_k8s_name(name, "pod name")
    _validate_k8s_name(ns, "namespace")
    return _kube(f"describe pod {name} -n {ns}")


@mcp.tool()
def kube_logs(name: str, ns: str = "default", container: str = "",
              tail: int = 200, since: str = "") -> str:
    """Get logs from a Kubernetes pod."""
    _validate_k8s_name(name, "pod name")
    _validate_k8s_name(ns, "namespace")
    if container:
        _validate_k8s_name(container, "container")
    if since:
        _validate_duration(since)
    cmd = f"logs {name} -n {ns} --tail={int(tail)}"
    if container:
        cmd += f" -c {container}"
    if since:
        cmd += f" --since={since}"
    return _kube(cmd)


@mcp.tool()
def kube_events(ns: str = "", kind: str = "", name: str = "",
                last: str = "30m") -> list[dict]:
    """Get recent Kubernetes events, sorted by time."""
    if ns:
        _validate_k8s_name(ns, "namespace")
    if name:
        _validate_k8s_name(name, "name")
    if last:
        _validate_duration(last)
    ns_flag = f"-n {ns}" if ns else "--all-namespaces"
    raw = _kube(f"get events {ns_flag} --sort-by='.lastTimestamp' -o json")
    data = _json.loads(raw)

    # Parse 'last' duration (e.g., "30m", "1h", "2h30m", "1d", "30s")
    cutoff = None
    if last:
        seconds = 0
        for match in _re.finditer(r'(\d+)([dhms])', last):
            val, unit = int(match.group(1)), match.group(2)
            if unit == 'd':
                seconds += val * 86400
            elif unit == 'h':
                seconds += val * 3600
            elif unit == 'm':
                seconds += val * 60
            else:
                seconds += val
        if seconds > 0:
            cutoff = _dt.now(_tz.utc) - _td(seconds=seconds)

    events = []
    for item in data.get("items", []):
        meta = item.get("metadata", {})
        involved = item.get("involvedObject", {})
        ts = item.get("lastTimestamp") or meta.get("creationTimestamp", "")

        if kind and involved.get("kind", "").lower() != kind.lower():
            continue
        if name and involved.get("name", "") != name:
            continue

        event = {
            "time": ts,
            "type": item.get("type"),
            "reason": item.get("reason"),
            "object": f"{involved.get('kind', '')}/{involved.get('name', '')}",
            "message": item.get("message", ""),
            "namespace": meta.get("namespace"),
        }
        events.append(event)

    # Time filter
    if cutoff:
        filtered = []
        for e in events:
            try:
                t = _dt.fromisoformat(e["time"].replace("Z", "+00:00"))
                if t >= cutoff:
                    filtered.append(e)
            except (ValueError, TypeError):
                filtered.append(e)
        events = filtered

    return events[-100:]


@mcp.tool()
def kube_rollout_status(deployment: str, ns: str = "default",
                        timeout: int = 60) -> str:
    """Check rollout status of a Kubernetes deployment."""
    _validate_k8s_name(deployment, "deployment")
    _validate_k8s_name(ns, "namespace")
    return _kube(f"rollout status deployment/{deployment} -n {ns} --timeout={int(timeout)}s",
                 timeout=int(timeout) + 10)


@mcp.tool()
def kube_image_present(image: str) -> dict:
    """Check if a container image is present in the containerd cache on the host."""
    _validate_image(image)
    try:
        raw = _ssh_exec("sudo crictl images --output json 2>/dev/null || echo '[]'")
        data = _json.loads(raw) if raw.startswith('{') or raw.startswith('[') else {}
        # Parse crictl JSON: images[].repoTags[] contains full image refs
        repo_tags = []
        for img in data.get("images", []):
            repo_tags.extend(img.get("repoTags", []))
        # Exact match or match with implicit :latest
        present = image in repo_tags or f"{image}:latest" in repo_tags
        return {"present": present, "image": image}
    except Exception as e:
        return {"present": False, "image": image, "error": str(e)}


@mcp.tool()
def flux_status() -> dict:
    """Get status of all Flux sources and kustomizations."""
    sources_raw = _ssh_exec("flux get sources all -A -o json 2>/dev/null || flux get sources git -A 2>&1")
    kust_raw = _ssh_exec("flux get kustomizations -A -o json 2>/dev/null || flux get kustomizations -A 2>&1")
    # Try JSON parse, fallback to raw text
    try:
        sources = _json.loads(sources_raw)
    except (ValueError, TypeError):
        sources = sources_raw
    try:
        kustomizations = _json.loads(kust_raw)
    except (ValueError, TypeError):
        kustomizations = kust_raw
    return {"sources": sources, "kustomizations": kustomizations}


@mcp.tool()
def flux_diff(kustomization: str = "flux-system") -> str:
    """Show what would change on next Flux reconciliation (dry-run diff)."""
    _validate_k8s_name(kustomization, "kustomization")
    try:
        return _flux(f"diff kustomization {kustomization}", timeout=120)
    except RuntimeError as e:
        return f"Diff failed (may need cluster access): {e}"


@mcp.tool()
def image_list_tags(repo: str, registry: str = "docker.io",
                    limit: int = 50) -> dict:
    """List available tags for a container image from a registry (Docker Hub, GHCR, lscr.io)."""
    _validate_image(repo)
    try:
        import httpx
        if registry == "docker.io":
            # Docker Hub v2 API
            # Normalize: "nginx" -> "library/nginx"
            if "/" not in repo:
                repo = f"library/{repo}"
            token_resp = httpx.get(
                f"https://auth.docker.io/token?service=registry.docker.io&scope=repository:{repo}:pull",
                timeout=10,
            )
            token = token_resp.json().get("token", "")
            resp = httpx.get(
                f"https://registry-1.docker.io/v2/{repo}/tags/list",
                headers={"Authorization": f"Bearer {token}"},
                timeout=10,
            )
            tags = resp.json().get("tags", [])
        elif registry in ("ghcr.io", "lscr.io"):
            resp = httpx.get(
                f"https://{registry}/v2/{repo}/tags/list",
                timeout=10,
            )
            tags = resp.json().get("tags", [])
        else:
            resp = httpx.get(
                f"https://{registry}/v2/{repo}/tags/list",
                timeout=10,
            )
            tags = resp.json().get("tags", [])
        return {"repo": repo, "registry": registry, "count": len(tags),
                "tags": tags[-limit:]}
    except Exception as e:
        return {"repo": repo, "registry": registry, "error": str(e)}


@mcp.tool()
def image_inspect(image: str) -> dict:
    """Inspect a container image manifest (digest, platforms, size)."""
    _validate_image(image)
    try:
        raw = _ssh_exec(f"skopeo inspect docker://{image} 2>&1 || "
                        f"crictl inspecti {image} 2>&1 || echo 'inspect unavailable'",
                        timeout=30)
        try:
            return _json.loads(raw)
        except (ValueError, TypeError):
            return {"raw": raw, "image": image}
    except Exception as e:
        return {"image": image, "error": str(e)}


@mcp.tool()
def image_compare_tags(repo: str, tag_a: str, tag_b: str,
                       registry: str = "docker.io") -> dict:
    """Compare two image tags by digest to check if they're the same image."""
    _validate_image(repo)
    try:
        import httpx
        if "/" not in repo and registry == "docker.io":
            repo = f"library/{repo}"

        if registry == "docker.io":
            token_resp = httpx.get(
                f"https://auth.docker.io/token?service=registry.docker.io&scope=repository:{repo}:pull",
                timeout=10,
            )
            token = token_resp.json().get("token", "")
            headers = {"Authorization": f"Bearer {token}",
                       "Accept": "application/vnd.docker.distribution.manifest.v2+json"}
            base = f"https://registry-1.docker.io/v2/{repo}/manifests"
        else:
            headers = {"Accept": "application/vnd.docker.distribution.manifest.v2+json"}
            base = f"https://{registry}/v2/{repo}/manifests"

        resp_a = httpx.head(f"{base}/{tag_a}", headers=headers, timeout=10)
        resp_b = httpx.head(f"{base}/{tag_b}", headers=headers, timeout=10)
        digest_a = resp_a.headers.get("docker-content-digest", "unknown")
        digest_b = resp_b.headers.get("docker-content-digest", "unknown")
        return {
            "repo": repo,
            "tag_a": tag_a, "digest_a": digest_a,
            "tag_b": tag_b, "digest_b": digest_b,
            "same_image": digest_a == digest_b and digest_a != "unknown",
        }
    except Exception as e:
        return {"repo": repo, "error": str(e)}


@mcp.tool()
def homelab_overview() -> dict:
    """Get a high-level overview of all homelab services in one call."""
    results = {}

    # Each service in a try/except so one failure doesn't kill the whole overview
    try:
        s = _sonarr()
        health = s.get("/health")
        results["sonarr"] = {"ok": len(health) == 0, "issues": len(health)}
    except Exception as e:
        results["sonarr"] = {"ok": False, "error": str(e)}

    try:
        r = _radarr()
        health = r.get("/health")
        results["radarr"] = {"ok": len(health) == 0, "issues": len(health)}
    except Exception as e:
        results["radarr"] = {"ok": False, "error": str(e)}

    try:
        p = _prowlarr()
        health = p.get("/health")
        results["prowlarr"] = {"ok": len(health) == 0, "issues": len(health)}
    except Exception as e:
        results["prowlarr"] = {"ok": False, "error": str(e)}

    try:
        q = _qbt()
        transfer = q.get("/transfer/info")
        results["qbittorrent"] = {
            "ok": True,
            "dl_speed": transfer.get("dl_info_speed", 0),
            "connection": transfer.get("connection_status"),
        }
    except Exception as e:
        results["qbittorrent"] = {"ok": False, "error": str(e)}

    try:
        px = _plex()
        identity = px.get("/")
        mc = identity.get("MediaContainer", {})
        sessions = px.get("/status/sessions")
        results["plex"] = {
            "ok": True,
            "version": mc.get("version"),
            "active_sessions": sessions.get("MediaContainer", {}).get("size", 0),
        }
    except Exception as e:
        results["plex"] = {"ok": False, "error": str(e)}

    try:
        hb = _homebridge()
        status = hb.get("/status/homebridge")
        results["homebridge"] = {"ok": status.get("status") == "up",
                                  "status": status.get("status")}
    except Exception as e:
        results["homebridge"] = {"ok": False, "error": str(e)}

    try:
        import httpx
        cfg = get_scrypted_config()
        resp = httpx.get(cfg.url, timeout=5, follow_redirects=True)
        results["scrypted"] = {"ok": resp.status_code in (200, 301, 302)}
    except Exception as e:
        results["scrypted"] = {"ok": False, "error": str(e)}

    try:
        h = _dirigera()
        if h is None:
            results["dirigera"] = {"ok": False, "error": "not configured"}
        else:
            lights = h.get_lights()
            results["dirigera"] = {
                "ok": True,
                "lights_total": len(lights),
                "lights_on": sum(1 for l in lights if getattr(l.attributes, "is_on", False)),
            }
    except Exception as e:
        results["dirigera"] = {"ok": False, "error": str(e)}

    # Kubernetes cluster summary
    try:
        pods = kube_pods()
        failing = [p for p in pods if p["phase"] not in ("Running", "Succeeded")]
        results["kubernetes"] = {
            "ok": len(failing) == 0,
            "total_pods": len(pods),
            "failing_pods": len(failing),
            "failing": [f"{p['namespace']}/{p['name']} ({p['phase']})" for p in failing[:5]],
        }
    except Exception as e:
        results["kubernetes"] = {"ok": False, "error": str(e)}

    # Resource pressure (node allocation)
    try:
        raw = _kube("describe node home 2>/dev/null | grep -A5 'Allocated resources'", timeout=15)
        results["resource_pressure"] = {"raw": raw.strip()}
    except Exception as e:
        results["resource_pressure"] = {"error": str(e)}

    return results


@mcp.tool()
def cert_manager_status() -> dict:
    """Report cert-manager health: ClusterIssuers + Certificates with Ready/age/secret.

    Returns ``{"installed": False}`` if the CRDs are not present (e.g. before
    cert-manager has reconciled). Read-only — never mutates.
    """
    # Probe for CRDs first; missing CRDs is a normal state, not an error.
    try:
        _kube("get crd clusterissuers.cert-manager.io --no-headers", timeout=15)
    except RuntimeError as e:
        if "NotFound" in str(e) or "not found" in str(e).lower():
            return {"installed": False, "reason": "cert-manager CRDs not present"}
        raise

    issuers: list[dict] = []
    try:
        raw = _kube("get clusterissuers -o json", timeout=20)
        for item in _json.loads(raw).get("items", []):
            meta = item.get("metadata", {})
            conds = item.get("status", {}).get("conditions", [])
            ready = next((c for c in conds if c.get("type") == "Ready"), {})
            issuers.append({
                "name": meta.get("name"),
                "ready": ready.get("status") == "True",
                "reason": ready.get("reason"),
                "message": ready.get("message"),
            })
    except RuntimeError as e:
        issuers = [{"error": str(e)}]

    certs: list[dict] = []
    try:
        raw = _kube("get certificates -A -o json", timeout=20)
        for item in _json.loads(raw).get("items", []):
            meta = item.get("metadata", {})
            spec = item.get("spec", {})
            status = item.get("status", {})
            conds = status.get("conditions", [])
            ready = next((c for c in conds if c.get("type") == "Ready"), {})
            certs.append({
                "namespace": meta.get("namespace"),
                "name": meta.get("name"),
                "ready": ready.get("status") == "True",
                "reason": ready.get("reason"),
                "secret": spec.get("secretName"),
                "issuer": spec.get("issuerRef", {}).get("name"),
                "not_after": status.get("notAfter"),
                "renewal_time": status.get("renewalTime"),
            })
    except RuntimeError as e:
        certs = [{"error": str(e)}]

    return {
        "installed": True,
        "issuers": issuers,
        "certificates": certs,
        "issuer_count": len(issuers),
        "cert_count": len(certs),
        "not_ready_count": sum(1 for c in certs if c.get("ready") is False),
    }


@mcp.tool()
def ingress_probe(host: str) -> dict:
    """HTTPS probe of a homelab ingress: status code, cert issuer/expiry, backend svc.

    The ``host`` parameter MUST match ``^[a-z0-9-]+\\.${HOMELAB_INGRESS_DOMAIN}$``
    where ``HOMELAB_INGRESS_DOMAIN`` is the operator's ingress apex —
    arbitrary hostnames are rejected to prevent SSRF (the probe runs from
    the homelab host, which has access to private networks).
    """
    host_re = ingress_host_re()
    if not host or not host_re.match(host):
        raise ValueError(
            f"Invalid host: {host!r} — must match {host_re.pattern}"
        )
    # Resolve to the operator's ingress IP so we test the cluster path,
    # not whatever public DNS resolves to.
    ingress_ip = homelab_ingress_ip()
    cmd = (
        f"curl -sI --max-time 10 --resolve {host}:443:{ingress_ip} "
        f"https://{host} -o /dev/null -w 'HTTP:%{{http_code}}\\n' && "
        f"echo --CERT-- && "
        f"echo | openssl s_client -servername {host} -connect {ingress_ip}:443 "
        f"-verify_return_error 2>/dev/null </dev/null | "
        f"openssl x509 -noout -subject -issuer -enddate 2>/dev/null"
    )
    try:
        out = _ssh_exec(cmd, timeout=20)
    except RuntimeError as e:
        return {"host": host, "reachable": False, "error": str(e)}

    result: dict = {"host": host, "reachable": True}
    for line in out.split("\n"):
        line = line.strip()
        if line.startswith("HTTP:"):
            try:
                result["http_code"] = int(line.split(":", 1)[1])
            except ValueError:
                pass
        elif line.startswith("subject="):
            result["cert_subject"] = line.partition("=")[2]
        elif line.startswith("issuer="):
            result["cert_issuer"] = line.partition("=")[2]
        elif line.startswith("notAfter="):
            result["cert_not_after"] = line.partition("=")[2]
    result["reachable"] = result.get("http_code") is not None
    return result


@mcp.tool()
def kube_pvc_usage(ns: str = "") -> list[dict]:
    """List PersistentVolumeClaims with capacity and bind status.

    Returns capacity from the PVC spec (NOT live ``df`` usage) — that would
    require ``kubectl exec`` which is an arbitrary-execution surface. For real
    disk usage, use ``host_disk`` or ``netdata`` metrics.
    """
    if ns:
        _validate_k8s_name(ns, "namespace")
    ns_flag = f"-n {ns}" if ns else "--all-namespaces"
    raw = _kube(f"get pvc {ns_flag} -o json", timeout=30)
    out = []
    for item in _json.loads(raw).get("items", []):
        meta = item.get("metadata", {})
        spec = item.get("spec", {})
        status = item.get("status", {})
        out.append({
            "namespace": meta.get("namespace"),
            "name": meta.get("name"),
            "phase": status.get("phase"),
            "capacity": status.get("capacity", {}).get("storage"),
            "requested": spec.get("resources", {}).get("requests", {}).get("storage"),
            "storage_class": spec.get("storageClassName"),
            "volume_name": spec.get("volumeName"),
            "access_modes": spec.get("accessModes", []),
        })
    return out


@mcp.tool()
def kube_resource_audit(ns: str = "") -> list[dict]:
    """Audit CPU/memory requests vs limits for all pods. Flags pods with no limits,
    no requests, or overcommitted resources."""
    if ns:
        _validate_k8s_name(ns, "namespace")
    ns_flag = f"-n {ns}" if ns else "--all-namespaces"
    raw = _kube(f"get pods {ns_flag} -o json", timeout=30)
    data = _json.loads(raw)
    results = []
    for item in data.get("items", []):
        meta = item.get("metadata", {})
        phase = item.get("status", {}).get("phase", "")
        if phase not in ("Running", "Pending"):
            continue
        for c in item.get("spec", {}).get("containers", []):
            res = c.get("resources", {})
            req = res.get("requests", {})
            lim = res.get("limits", {})
            warnings = []
            if not req:
                warnings.append("no_requests")
            if not lim:
                warnings.append("no_limits")
            results.append({
                "namespace": meta.get("namespace"),
                "pod": meta.get("name"),
                "container": c.get("name"),
                "cpu_request": req.get("cpu"),
                "cpu_limit": lim.get("cpu"),
                "memory_request": req.get("memory"),
                "memory_limit": lim.get("memory"),
                "warnings": warnings,
            })
    return results


@mcp.tool()
def kube_oom_events(ns: str = "", last: str = "1h") -> list[dict]:
    """Find OOMKilled containers across the cluster in the last N hours."""
    if ns:
        _validate_k8s_name(ns, "namespace")
    if last:
        _validate_duration(last)
    ns_flag = f"-n {ns}" if ns else "--all-namespaces"
    raw = _kube(f"get pods {ns_flag} -o json", timeout=30)
    data = _json.loads(raw)
    oom = []
    for item in data.get("items", []):
        meta = item.get("metadata", {})
        for cs in item.get("status", {}).get("containerStatuses", []):
            last_state = cs.get("lastState", {}).get("terminated", {})
            if last_state.get("reason") == "OOMKilled":
                oom.append({
                    "namespace": meta.get("namespace"),
                    "pod": meta.get("name"),
                    "container": cs.get("name"),
                    "exit_code": last_state.get("exitCode"),
                    "finished_at": last_state.get("finishedAt"),
                    "restart_count": cs.get("restartCount", 0),
                })
    return oom


@mcp.tool()
def kube_crashloop_pods(threshold: int = 5) -> list[dict]:
    """Find pods with restart count above threshold, with last restart reason."""
    raw = _kube("get pods --all-namespaces -o json", timeout=30)
    data = _json.loads(raw)
    crashers = []
    for item in data.get("items", []):
        meta = item.get("metadata", {})
        for cs in item.get("status", {}).get("containerStatuses", []):
            rc = cs.get("restartCount", 0)
            if rc > threshold:
                last_state = cs.get("lastState", {}).get("terminated", {})
                crashers.append({
                    "namespace": meta.get("namespace"),
                    "pod": meta.get("name"),
                    "container": cs.get("name"),
                    "restarts": rc,
                    "last_reason": last_state.get("reason", "Unknown"),
                    "last_exit_code": last_state.get("exitCode"),
                    "last_finished": last_state.get("finishedAt"),
                })
    crashers.sort(key=lambda x: x["restarts"], reverse=True)
    return crashers


@mcp.tool()
def kube_previous_logs(name: str, ns: str = "default",
                       container: str = "", tail: int = 200) -> str:
    """Get logs from the PREVIOUS container incarnation (pre-crash). Critical for
    diagnosing OOMKill and CrashLoopBackOff."""
    _validate_k8s_name(name, "pod name")
    _validate_k8s_name(ns, "namespace")
    if container:
        _validate_k8s_name(container, "container")
    cmd = f"logs {name} -n {ns} --previous --tail={int(tail)}"
    if container:
        cmd += f" -c {container}"
    return _kube(cmd)


@mcp.tool()
def kube_init_container_logs(name: str, ns: str = "default") -> str:
    """Get logs from all init containers of a pod. Init container failures are
    invisible in normal ``kube_logs`` calls."""
    _validate_k8s_name(name, "pod name")
    _validate_k8s_name(ns, "namespace")
    raw = _kube(f"get pod {name} -n {ns} -o json", timeout=15)
    pod = _json.loads(raw)
    init_containers = pod.get("spec", {}).get("initContainers", [])
    if not init_containers:
        return "No init containers in this pod."
    logs = []
    for ic in init_containers:
        ic_name = ic.get("name", "unknown")
        try:
            log = _kube(f"logs {name} -n {ns} -c {ic_name} --tail=100")
            logs.append(f"=== {ic_name} ===\n{log}")
        except RuntimeError as e:
            logs.append(f"=== {ic_name} === ERROR: {e}")
    return "\n\n".join(logs)


@mcp.tool()
def kube_netpol_list(ns: str = "") -> list[dict]:
    """List all NetworkPolicies with parsed ingress/egress rules."""
    if ns:
        _validate_k8s_name(ns, "namespace")
    ns_flag = f"-n {ns}" if ns else "--all-namespaces"
    raw = _kube(f"get networkpolicy {ns_flag} -o json", timeout=20)
    data = _json.loads(raw)
    policies = []
    for item in data.get("items", []):
        meta = item.get("metadata", {})
        spec = item.get("spec", {})
        policies.append({
            "namespace": meta.get("namespace"),
            "name": meta.get("name"),
            "pod_selector": spec.get("podSelector", {}),
            "policy_types": spec.get("policyTypes", []),
            "ingress_rules": len(spec.get("ingress", [])),
            "egress_rules": len(spec.get("egress", [])),
        })
    return policies


@mcp.tool()
def kube_ingress_validate() -> list[dict]:
    """Cross-check every Ingress: host → service → endpoints → running pod.
    Returns issues found (empty list = all healthy)."""
    raw = _kube("get ingress --all-namespaces -o json", timeout=20)
    data = _json.loads(raw)
    issues = []
    for item in data.get("items", []):
        meta = item.get("metadata", {})
        ns = meta.get("namespace", "default")
        for rule in item.get("spec", {}).get("rules", []):
            host = rule.get("host", "")
            for path in rule.get("http", {}).get("paths", []):
                svc_name = path.get("backend", {}).get("service", {}).get("name", "")
                svc_port = path.get("backend", {}).get("service", {}).get("port", {})
                if not svc_name:
                    continue
                # Check service exists
                try:
                    svc_raw = _kube(f"get service {svc_name} -n {ns} -o json", timeout=10)
                    _json.loads(svc_raw)
                except RuntimeError:
                    issues.append({
                        "host": host, "service": svc_name, "namespace": ns,
                        "issue": "service_not_found",
                    })
                    continue
                # Check endpoints
                try:
                    ep_raw = _kube(f"get endpoints {svc_name} -n {ns} -o json", timeout=10)
                    ep = _json.loads(ep_raw)
                    addresses = []
                    for subset in ep.get("subsets", []):
                        addresses.extend(subset.get("addresses", []))
                    if not addresses:
                        issues.append({
                            "host": host, "service": svc_name, "namespace": ns,
                            "issue": "no_ready_endpoints",
                        })
                except RuntimeError:
                    issues.append({
                        "host": host, "service": svc_name, "namespace": ns,
                        "issue": "endpoints_error",
                    })
    return issues


@mcp.tool()
def kube_service_endpoints(ns: str = "") -> list[dict]:
    """Find services with zero ready endpoints (broken service wiring)."""
    if ns:
        _validate_k8s_name(ns, "namespace")
    ns_flag = f"-n {ns}" if ns else "--all-namespaces"
    raw = _kube(f"get endpoints {ns_flag} -o json", timeout=20)
    data = _json.loads(raw)
    empty = []
    for item in data.get("items", []):
        meta = item.get("metadata", {})
        name = meta.get("name", "")
        # Skip k8s internal services
        if name in ("kubernetes", "kube-dns"):
            continue
        subsets = item.get("subsets", [])
        total_addresses = sum(len(s.get("addresses", [])) for s in subsets)
        if total_addresses == 0:
            empty.append({
                "namespace": meta.get("namespace"),
                "service": name,
                "ready_endpoints": 0,
            })
    return empty


@mcp.tool()
def dns_completeness_check() -> dict:
    """Compare all Ingress hosts vs Cloudflare DNS records. Returns missing records."""
    # Get all ingress hosts
    raw = _kube("get ingress --all-namespaces -o json", timeout=20)
    data = _json.loads(raw)
    ingress_hosts = set()
    for item in data.get("items", []):
        for rule in item.get("spec", {}).get("rules", []):
            host = rule.get("host", "")
            if host:
                ingress_hosts.add(host)
    # Get Cloudflare DNS records (uses CF_DEFAULT_ZONE).
    zone = cf_default_zone()
    domain_suffix = "." + zone
    try:
        cf_records = cf_dns_list(zone=zone)
        cf_names = {r.get("name") for r in cf_records.get("records", [])}
    except Exception as e:
        return {"error": f"Failed to query Cloudflare: {e}", "ingress_hosts": sorted(ingress_hosts)}

    missing = sorted(ingress_hosts - cf_names)
    extra = sorted({n for n in cf_names if n.endswith(domain_suffix)} - ingress_hosts)
    return {
        "ingress_hosts": sorted(ingress_hosts),
        "dns_records": sorted(n for n in cf_names if n.endswith(domain_suffix)),
        "missing_dns": missing,
        "extra_dns": extra,
        "all_complete": len(missing) == 0,
    }


@mcp.tool()
def kube_orphan_cleanup_preview() -> dict:
    """Preview orphan resources: stale ReplicaSets (0 replicas), completed/failed Jobs,
    evicted pods. Read-only — returns counts only, does not delete."""
    # Stale ReplicaSets
    raw = _kube("get rs --all-namespaces -o json", timeout=30)
    rs_data = _json.loads(raw)
    stale_rs = [
        f"{item['metadata']['namespace']}/{item['metadata']['name']}"
        for item in rs_data.get("items", [])
        if item.get("spec", {}).get("replicas", 1) == 0
    ]
    # Completed/Failed Jobs
    raw = _kube("get jobs --all-namespaces -o json", timeout=20)
    job_data = _json.loads(raw)
    old_jobs = []
    for item in job_data.get("items", []):
        status = item.get("status", {})
        if status.get("succeeded") or status.get("failed"):
            old_jobs.append(
                f"{item['metadata']['namespace']}/{item['metadata']['name']}"
            )
    # Evicted pods
    raw = _kube("get pods --all-namespaces --field-selector=status.phase=Failed -o json", timeout=20)
    pod_data = _json.loads(raw)
    evicted = [
        f"{item['metadata']['namespace']}/{item['metadata']['name']}"
        for item in pod_data.get("items", [])
        if item.get("status", {}).get("reason") == "Evicted"
    ]
    return {
        "stale_replicasets": len(stale_rs),
        "stale_rs_sample": stale_rs[:10],
        "completed_jobs": len(old_jobs),
        "completed_jobs_sample": old_jobs[:10],
        "evicted_pods": len(evicted),
        "evicted_pods_sample": evicted[:10],
    }


@mcp.tool()
def host_mount_status() -> list[dict]:
    """Check all mount points: mounted/stale/offline status. Detects NFS issues
    and unmounted external drives."""
    output = _ssh_exec("mount | grep -vE 'tmpfs|proc|sys|cgroup|devpts|securityfs|debugfs|snap|fuse'")
    mounts = []
    for line in output.split("\n"):
        parts = line.split()
        if len(parts) >= 6:
            device = parts[0]
            mount_point = parts[2]
            fs_type = parts[4]
            mounts.append({
                "device": device,
                "mount_point": mount_point,
                "fs_type": fs_type,
                "status": "mounted",
            })
    # Check expected mounts
    expected = ["/media/nas", "/media/external_drive", "/mnt/internal_drive"]
    mounted_paths = {m["mount_point"] for m in mounts}
    for exp in expected:
        if exp not in mounted_paths:
            mounts.append({
                "device": "?",
                "mount_point": exp,
                "fs_type": "?",
                "status": "NOT_MOUNTED",
            })
    return mounts


@mcp.tool()
def host_reboot_required() -> dict:
    """Check if the host needs a reboot (kernel update, etc.)."""
    try:
        result = _ssh_exec("test -f /var/run/reboot-required && cat /var/run/reboot-required || echo 'NO'")
        required = result.strip() != "NO"
        return {
            "reboot_required": required,
            "message": result.strip() if required else "No reboot required",
        }
    except RuntimeError as e:
        return {"reboot_required": False, "error": str(e)}


@mcp.tool()
def kube_log_errors(name: str, ns: str = "default", tail: int = 500,
                    pattern: str = "ERROR|FATAL|PANIC|Exception") -> list[dict]:
    """Scan pod logs for error patterns with dedup and count."""
    _validate_k8s_name(name, "pod name")
    _validate_k8s_name(ns, "namespace")
    # Validate pattern — only allow safe regex chars
    if not _re.match(r'^[a-zA-Z0-9|_ .-]+$', pattern):
        raise ValueError(f"Invalid pattern: {pattern!r}")
    raw = _kube(f"logs {name} -n {ns} --tail={int(tail)}")
    errors = {}
    for line in raw.split("\n"):
        if _re.search(pattern, line, _re.IGNORECASE):
            # Dedup by first 80 chars
            key = line.strip()[:80]
            if key in errors:
                errors[key]["count"] += 1
            else:
                errors[key] = {"line": line.strip(), "count": 1}
    return sorted(errors.values(), key=lambda x: x["count"], reverse=True)[:50]


@mcp.tool()
def host_os_version() -> dict:
    """Get Ubuntu release, kernel, microk8s, and snap versions."""
    cmd = (
        "echo OS:$(lsb_release -ds 2>/dev/null) ; "
        "echo KERNEL:$(uname -r) ; "
        "echo MICROK8S:$(snap list microk8s 2>/dev/null | tail -1 | awk '{print $2}') ; "
        "echo DOCKER:$(docker --version 2>/dev/null | head -1)"
    )
    output = _ssh_exec(cmd)
    result = {}
    for line in output.split("\n"):
        if ":" in line:
            key, _, val = line.partition(":")
            result[key.strip().lower()] = val.strip()
    return result


@mcp.tool()
def backup_status() -> dict:
    """Check restic backup timer status, last run time, and result."""
    timer = _ssh_exec("systemctl status restic-backup.timer 2>/dev/null | head -6")
    journal = _ssh_exec("journalctl -u restic-backup.service --no-pager -n 5 2>/dev/null")
    return {"timer": timer, "last_runs": journal}


@mcp.tool()
def backup_snapshots(last: int = 10) -> list[dict]:
    """List restic backup snapshots with dates and sizes."""
    try:
        raw = _ssh_exec(
            f"restic snapshots --json --last {int(last)} 2>/dev/null",
            timeout=30,
        )
        snapshots = _json.loads(raw) if raw.strip().startswith("[") else []
        return [
            {
                "id": s.get("short_id"),
                "time": s.get("time"),
                "hostname": s.get("hostname"),
                "paths": s.get("paths", []),
            }
            for s in snapshots
        ]
    except Exception as e:
        return [{"error": str(e)}]


@mcp.tool()
def netdata_query(chart: str, after: int = -600, before: int = 0,
                  points: int = 10) -> dict:
    """Query Netdata API for any metric chart. Uses HTTP directly (no SSH).

    Args:
        chart: Netdata chart name (e.g. 'system.cpu', 'system.ram', 'disk_space._')
        after: Seconds relative to now (negative = past). Default -600 (10 min ago).
        before: Seconds relative to now. Default 0 (now).
        points: Number of data points. Default 10.
    """
    # Validate chart name
    if not chart or not _re.match(r'^[a-zA-Z0-9][a-zA-Z0-9._/-]*$', chart) or len(chart) > 100:
        raise ValueError(f"Invalid chart name: {chart!r}")
    import httpx
    try:
        r = httpx.get(
            f"http://netdata.default.svc:19999/api/v1/data",
            params={"chart": chart, "after": after, "before": before, "points": points,
                    "format": "json"},
            timeout=15.0,
        )
        r.raise_for_status()
        return r.json()
    except Exception as e:
        return {"error": str(e), "chart": chart}


@mcp.tool()
def ansible_inventory() -> dict:
    """List Ansible inventory hosts and groups (read-only)."""
    try:
        raw = _ssh_exec("cat ~/src/homelab/ansible/inventories/home/hosts.yml 2>/dev/null || "
                        "cat ~/src/homelab/ansible/inventories/home/hosts 2>/dev/null || "
                        "echo 'inventory not found'")
        return {"raw": raw}
    except RuntimeError as e:
        return {"error": str(e)}


@mcp.tool()
def ansible_playbook_list() -> list[dict]:
    """List available Ansible playbooks with descriptions."""
    try:
        raw = _ssh_exec("ls ~/src/homelab/ansible/playbooks/*.yml 2>/dev/null")
        playbooks = []
        for line in raw.split("\n"):
            name = line.strip().split("/")[-1] if line.strip() else ""
            if name:
                # Try to get first comment line as description
                try:
                    desc = _ssh_exec(f"head -3 {line.strip()} 2>/dev/null | grep '#' | head -1")
                    desc = desc.strip().lstrip("#").strip()
                except RuntimeError:
                    desc = ""
                playbooks.append({"name": name, "path": line.strip(), "description": desc})
        return playbooks
    except RuntimeError as e:
        return [{"error": str(e)}]


@mcp.tool()
def kube_top_pods(ns: str = "", sort: str = "memory") -> list[dict]:
    """Get actual resource usage per pod (requires metrics-server).
    Sort by 'memory' or 'cpu'."""
    if ns:
        _validate_k8s_name(ns, "namespace")
    if sort not in ("memory", "cpu"):
        raise ValueError(f"sort must be 'memory' or 'cpu', got {sort!r}")
    ns_flag = f"-n {ns}" if ns else "--all-namespaces"
    try:
        raw = _kube(f"top pods {ns_flag} --sort-by={sort} --no-headers", timeout=15)
        pods = []
        for line in raw.split("\n"):
            parts = line.split()
            if len(parts) >= 3:
                # all-namespaces: NS NAME CPU MEM
                # single ns: NAME CPU MEM
                if ns:
                    pods.append({"name": parts[0], "cpu": parts[1], "memory": parts[2]})
                else:
                    pods.append({"namespace": parts[0], "name": parts[1],
                                 "cpu": parts[2], "memory": parts[3] if len(parts) > 3 else "?"})
        return pods
    except RuntimeError as e:
        if "metrics" in str(e).lower() or "not available" in str(e).lower():
            return [{"error": "Metrics API not available. Enable metrics-server addon: sudo microk8s enable metrics-server"}]
        return [{"error": str(e)}]


@mcp.tool()
def host_syslog_errors(hours: int = 4, level: str = "err,crit,alert") -> list[dict]:
    """Parse syslog for errors in the last N hours."""
    if not _re.match(r'^[a-z,]+$', level):
        raise ValueError(f"Invalid level: {level!r}")
    raw = _ssh_exec(f"journalctl --priority={level} --since='{int(hours)} hours ago' --no-pager -n 100 2>/dev/null")
    entries = []
    for line in raw.split("\n"):
        if line.strip():
            entries.append({"line": line.strip()})
    return entries[:100]


@mcp.tool()
def host_dmesg_errors(level: str = "err,crit,alert") -> list[dict]:
    """Get hardware errors from dmesg (disk, USB, memory issues)."""
    if not _re.match(r'^[a-z,]+$', level):
        raise ValueError(f"Invalid level: {level!r}")
    try:
        raw = _ssh_exec(f"sudo dmesg --level={level} 2>/dev/null | tail -50")
        return [{"line": line.strip()} for line in raw.split("\n") if line.strip()]
    except RuntimeError as e:
        return [{"error": str(e)}]


@mcp.tool()
def host_auth_log(tail: int = 50) -> list[dict]:
    """Recent SSH logins and failed auth attempts."""
    try:
        raw = _ssh_exec(f"sudo tail -n {int(tail)} /var/log/auth.log 2>/dev/null")
        return [{"line": line.strip()} for line in raw.split("\n") if line.strip()]
    except RuntimeError as e:
        return [{"error": str(e)}]


@mcp.tool()
def audit_tail(n: int = 50, tool: str = "") -> dict:
    """Return the last ``n`` lines of the MCP audit log, optionally filtered by tool name.

    Args:
        n: How many lines to return (capped at 1000 to bound memory).
        tool: Optional exact tool-name filter (regex injection is rejected).
    """
    if not isinstance(n, int) or n < 1:
        raise ValueError("n must be a positive int")
    if n > 1000:
        n = 1000
    if tool and not _AUDIT_TOOL_RE.match(tool):
        raise ValueError(f"Invalid tool filter: {tool!r}")

    if not _AUDIT_LOG_PATH.exists():
        return {"path": str(_AUDIT_LOG_PATH), "exists": False, "lines": []}

    # Read the whole file and slice — audit logs are bounded by logrotate.
    with open(_AUDIT_LOG_PATH, encoding="utf-8", errors="replace") as fh:
        all_lines = fh.readlines()

    lines: list[dict] = []
    for raw in all_lines[-(n * 4):]:  # over-read so post-filter still has n
        parts = raw.rstrip("\n").split("\t")
        if len(parts) < 4:
            continue
        ts, name, params, status = parts[0], parts[1], parts[2], parts[3]
        if tool and name != tool:
            continue
        lines.append({"ts": ts, "tool": name, "params": params, "status": status})

    return {
        "path": str(_AUDIT_LOG_PATH),
        "exists": True,
        "count": len(lines[-n:]),
        "lines": lines[-n:],
    }

