"""Shared per-process MCP runtime state and helpers.

Generated by tools/phase_1_0_split_server.py from
mcp/src/homelab_mcp/server.py at the Phase 1.0 refactor. Tool source is
byte-faithful with the pre-split monolith. Edit the generator (and the
inventory) rather than hand-patching this file.
"""

from __future__ import annotations

# --- Imports (mirrors original server.py) ---
import os

import subprocess

from homelab_mcp.app import create_mcp

from homelab_mcp.audit import audit as _write_audit

from homelab_mcp.audit import configure_audit_logger

from homelab_mcp.clients import (
    ServarrClient,
    QbtClient,
    PlexClient,
    HomebridgeClient,
    Mylar3Client,
    get_sonarr_config,
    get_radarr_config,
    get_lidarr_config,
    get_readarr_config,
    get_mylar3_config,
    get_prowlarr_config,
    get_qbt_config,
    get_plex_config,
    get_homebridge_config,
    get_scrypted_config,
    get_dirigera_config,
    get_unifi_config,
    env,
)

from homelab_mcp.policy import WRITE_TOOLS as _POLICY_WRITE_TOOLS

from homelab_mcp.policy import check_readonly as _policy_check_readonly

from homelab_mcp.settings import (
    audit_log_path,
    cf_allowed_zones,
    cf_default_zone,
    env_flag,
    homelab_ingress_ip,
    ingress_host_re,
    require_env,
)

import json as _json

import re as _re

from datetime import datetime as _dt, timedelta as _td, timezone as _tz

import asyncio as _aio

import json as _json


# --- Singleton state ---
mcp = create_mcp()

_clients: dict = {}

_AUDIT_LOG_PATH = audit_log_path()

_audit_logger = configure_audit_logger(_AUDIT_LOG_PATH)

_READONLY = env_flag("HOMELAB_MCP_READONLY")

_WRITE_TOOLS = _POLICY_WRITE_TOOLS

_K8S_NAME_RE = _re.compile(r'^[a-z0-9]([a-z0-9.\-]*[a-z0-9])?$')

_IMAGE_RE = _re.compile(r'^[a-zA-Z0-9][a-zA-Z0-9_./:@\-]*$')

_DURATION_RE = _re.compile(r'^(\d+[dhms])+$')

_DNS_NAME_RE = _re.compile(r'^[a-z0-9][a-z0-9.\-]*[a-z0-9]$')

_PROWLARR_DEF_RE = _re.compile(r'^[a-zA-Z0-9_\-]{2,64}$')

_AUDIT_TOOL_RE = _re.compile(r'^[a-z][a-z0-9_]{1,63}$')


# --- Helpers used by tools across multiple domain modules ---
def _audit(tool_name: str, params: dict, result_summary: str = "ok") -> None:
    """Compatibility wrapper for the extracted audit helper."""
    _write_audit(_audit_logger, tool_name, params, result_summary)

def _check_readonly(tool_name: str) -> None:
    """Raise if the server is in readonly mode and the tool mutates.

    Emits a `rejected_readonly` audit line before raising so the operator can
    distinguish blocked attempts from successful calls in audit.log.
    """
    _policy_check_readonly(tool_name, readonly=_READONLY, audit=_audit)

def _sonarr() -> ServarrClient:
    if "sonarr" not in _clients:
        _clients["sonarr"] = ServarrClient(get_sonarr_config(), api_version="v3")
    return _clients["sonarr"]

def _radarr() -> ServarrClient:
    if "radarr" not in _clients:
        _clients["radarr"] = ServarrClient(get_radarr_config(), api_version="v3")
    return _clients["radarr"]

def _lidarr() -> ServarrClient:
    if "lidarr" not in _clients:
        _clients["lidarr"] = ServarrClient(get_lidarr_config(), api_version="v1")
    return _clients["lidarr"]

def _readarr() -> ServarrClient:
    if "readarr" not in _clients:
        _clients["readarr"] = ServarrClient(get_readarr_config(), api_version="v1")
    return _clients["readarr"]

def _mylar3() -> Mylar3Client:
    if "mylar3" not in _clients:
        _clients["mylar3"] = Mylar3Client(get_mylar3_config())
    return _clients["mylar3"]

def _prowlarr() -> ServarrClient:
    if "prowlarr" not in _clients:
        _clients["prowlarr"] = ServarrClient(get_prowlarr_config(), api_version="v1")
    return _clients["prowlarr"]

def _qbt() -> QbtClient:
    if "qbt" not in _clients:
        _clients["qbt"] = QbtClient(get_qbt_config())
    return _clients["qbt"]

def _plex() -> PlexClient:
    if "plex" not in _clients:
        _clients["plex"] = PlexClient(get_plex_config())
    return _clients["plex"]

def _homebridge() -> HomebridgeClient:
    if "homebridge" not in _clients:
        _clients["homebridge"] = HomebridgeClient(get_homebridge_config())
    return _clients["homebridge"]

def _ssh_exec(command: str, timeout: int = 60) -> str:
    """Execute a command on the homelab host via SSH."""
    host = require_env(
        "HOMELAB_HOST",
        hint="set to your homelab SSH host (no default; the server is meant to be deployment-agnostic)",
    )
    user = require_env(
        "HOMELAB_SSH_USER",
        hint="set to the SSH user on HOMELAB_HOST",
    )
    key_path = env("HOMELAB_SSH_KEY", "")

    ssh_cmd = ["ssh", "-o", "StrictHostKeyChecking=accept-new",
               "-o", "ConnectTimeout=10"]
    if key_path:
        ssh_cmd.extend(["-i", key_path])
    ssh_cmd.extend([f"{user}@{host}", command])

    result = subprocess.run(ssh_cmd, capture_output=True, text=True, timeout=timeout)
    if result.returncode != 0:
        raise RuntimeError(f"SSH failed: {result.stderr.strip()}")
    return result.stdout.strip()

def _validate_k8s_name(value: str, param: str) -> str:
    """Validate a Kubernetes resource name. Raises ValueError on invalid input."""
    if not value or len(value) > 253 or not _K8S_NAME_RE.match(value):
        raise ValueError(f"Invalid {param}: {value!r} — must be a valid K8s name (lowercase alnum + hyphens)")
    return value

def _validate_image(value: str) -> str:
    """Validate a container image reference. Raises ValueError on invalid input."""
    if not value or len(value) > 500 or not _IMAGE_RE.match(value):
        raise ValueError(f"Invalid image ref: {value!r}")
    return value

def _validate_duration(value: str) -> str:
    """Validate a duration string like '30m', '1h', '2h30m'. Raises ValueError on invalid input."""
    if not value:
        return value
    if not _DURATION_RE.match(value):
        raise ValueError(f"Invalid duration: {value!r} — use digits + h/m/s/d (e.g., '30m', '1h', '2d')")
    return value

def _kube(cmd: str, timeout: int = 60) -> str:
    """Run a kubectl command on the host via SSH."""
    return _ssh_exec(f"kubectl {cmd}", timeout=timeout)

def _flux(cmd: str, timeout: int = 60) -> str:
    """Run a flux command on the host via SSH."""
    return _ssh_exec(f"flux {cmd}", timeout=timeout)

def _dirigera():
    """Lazy-init Dirigera hub client. Returns None if not configured."""
    if "dirigera" in _clients:
        return _clients["dirigera"]
    cfg = get_dirigera_config()
    if not cfg.url or not cfg.api_key:
        return None
    try:
        import dirigera as _dlib
        # The lib uses HTTPS to https://<ip>:8443 by default; we just pass the IP.
        hub = _dlib.Hub(token=cfg.api_key, ip_address=cfg.url)
        _clients["dirigera"] = hub
        return hub
    except Exception as e:
        _clients["dirigera"] = None
        raise RuntimeError(f"Dirigera init failed: {e}") from e

def _need_dirigera():
    h = _dirigera()
    if h is None:
        raise RuntimeError(
            "Dirigera not configured. Set DIRIGERA_IP and DIRIGERA_TOKEN. "
            "Pair once with: generate-token <hub-ip>"
        )
    return h

def _dev_summary(d) -> dict:
    """Compact summary of any dirigera device, defensive against missing attrs."""
    a = getattr(d, "attributes", None)
    return {
        "id": getattr(d, "id", None),
        "name": getattr(a, "custom_name", None) if a else None,
        "type": getattr(d, "device_type", None) or getattr(d, "type", None),
        "model": getattr(a, "model", None) if a else None,
        "room": getattr(getattr(d, "room", None), "name", None),
        "reachable": getattr(d, "is_reachable", None),
    }

def _find_light(h, name_or_id: str):
    for l in h.get_lights():
        if l.id == name_or_id or l.attributes.custom_name == name_or_id:
            return l
    raise RuntimeError(f"Light not found: {name_or_id}")

def _apple_devices_map() -> dict:
    raw = env("APPLE_TV_DEVICES", default="{}")
    try:
        return _json.loads(raw) if raw else {}
    except Exception as e:
        raise RuntimeError(f"APPLE_TV_DEVICES is not valid JSON: {e}")

def _apple_run(coro):
    """Run a pyatv coroutine to completion in a fresh event loop."""
    try:
        loop = _aio.new_event_loop()
        return loop.run_until_complete(coro)
    finally:
        try:
            loop.close()
        except Exception:
            pass

async def _apple_connect(name: str):
    """Connect to a configured Apple device by friendly name."""
    import pyatv
    from pyatv.const import Protocol
    devices = _apple_devices_map()
    if name not in devices:
        raise RuntimeError(
            f"Apple device {name!r} not configured. Known: {list(devices)}. "
            "Run apple_scan, then pair via atvremote."
        )
    cfg = devices[name]
    identifier = cfg["identifier"]
    creds = cfg.get("credentials", {})

    loop = _aio.get_event_loop()
    found = await pyatv.scan(loop=loop, identifier=identifier, timeout=5)
    if not found:
        raise RuntimeError(f"Device {name!r} (id={identifier}) not found on LAN")
    conf = found[0]
    # Re-attach saved credentials per protocol
    name_to_proto = {
        "companion": Protocol.Companion,
        "airplay":   Protocol.AirPlay,
        "raop":      Protocol.RAOP,
        "mrp":       Protocol.MRP,
    }
    for proto_name, cred in creds.items():
        proto = name_to_proto.get(proto_name)
        if proto:
            conf.set_credentials(proto, cred)
    atv = await pyatv.connect(conf, loop=loop)
    return atv, conf

def _unifi_run(coro):
    """Run a UniFi coroutine to completion in a fresh aiohttp session."""
    async def _wrap():
        import aiohttp
        cfg = get_unifi_config()
        if not cfg["host"]:
            raise RuntimeError("UniFi not configured. Set UNIFI_HOST/USER/PASS.")
        from aiounifi.controller import Controller
        from aiounifi.models.configuration import Configuration
        async with aiohttp.ClientSession(cookie_jar=aiohttp.CookieJar(unsafe=True)) as session:
            controller = Controller(Configuration(
                session,
                cfg["host"],
                username=cfg["username"],
                password=cfg["password"],
                port=cfg["port"],
                site=cfg["site"],
                ssl_context=False,           # UDM uses self-signed cert
            ))
            # Retry login once with backoff on UDM auth rate-limit.
            from aiounifi.errors import AuthenticationRateLimitError, ResponseError
            for attempt in range(2):
                try:
                    await controller.login()
                    break
                except (AuthenticationRateLimitError, ResponseError) as e:
                    msg = str(e)
                    if "429" not in msg and "RATE" not in msg.upper() and "LIMIT" not in msg.upper():
                        raise
                    if attempt == 1:
                        raise RuntimeError(
                            "UniFi rate-limited login (429). Wait 5–15 min before retrying. "
                            f"Underlying: {type(e).__name__}: {msg[:200]}"
                        ) from e
                    await _aio.sleep(15)
            return await coro(controller)
    loop = _aio.new_event_loop()
    try:
        return loop.run_until_complete(_wrap())
    finally:
        loop.close()

def _client_summary(c) -> dict:
    """Compact JSON-safe view of a UniFi client."""
    return {
        "mac":        c.mac,
        "ip":         c.ip,
        "hostname":   c.hostname or c.name or "",
        "name":       c.name,
        "is_wired":   c.is_wired,
        "is_guest":   c.is_guest,
        "blocked":    c.blocked,
        "essid":      c.essid,
        "ap_mac":     c.access_point_mac,
        "switch_mac": getattr(c, "switch_mac", "") or "",
        "vlan":       getattr(c, "vlan", None),
        "uptime":     getattr(c, "uptime", 0),
        "last_seen":  c.last_seen,
        "rx_kbps":    getattr(c, "rx_rate", 0),
        "tx_kbps":    getattr(c, "tx_rate", 0),
    }

def _resolve_mac(controller, name_or_mac: str) -> str:
    """Accept a MAC, hostname, or display name; return the matching MAC."""
    if ":" in name_or_mac and len(name_or_mac) == 17:
        return name_or_mac.lower()
    needle = name_or_mac.lower()
    for c in controller.clients.values():
        for f in (c.hostname, c.name, c.device_name):
            if f and needle == f.lower():
                return c.mac
    # also check known clients (offline)
    for c in controller.clients_all.values():
        for f in (c.hostname, c.name):
            if f and needle == f.lower():
                return c.mac
    raise RuntimeError(f"No UniFi client found matching {name_or_mac!r}")

def _cf_token() -> str:
    """Read the Cloudflare API token from env or fail loudly."""
    tok = env("CLOUDFLARE_API_TOKEN") or env("CF_DNS_API_TOKEN")
    if not tok:
        raise RuntimeError(
            "CLOUDFLARE_API_TOKEN not set. Either export it or pull from the "
            "in-cluster secret: "
            "kubectl get secret cloudflare-api-token -o jsonpath='{.data.CF_DNS_API_TOKEN}' | base64 -d"
        )
    return tok

def _cf_get(path: str, **params) -> dict:
    """GET against the Cloudflare v4 API."""
    import httpx
    r = httpx.get(
        f"https://api.cloudflare.com/client/v4{path}",
        headers={"Authorization": f"Bearer {_cf_token()}"},
        params=params,
        timeout=15.0,
    )
    r.raise_for_status()
    return r.json()

