"""Homelab MCP monolith server orchestrator.

Generated by tools/phase_1_0_split_server.py at the Phase 1.0 refactor.

Imports the shared ``_runtime`` module (which constructs the singleton
``mcp`` instance, configures the audit logger, and exposes helpers) and
each ``tools/*`` domain module (which registers its tools onto ``mcp``
as a side effect of import). The result is the same 133-tool monolith
image as the pre-refactor monolith — the only change is internal
layout.
"""
from __future__ import annotations

# Shared singleton state (mcp instance, audit logger, client factories,
# policy helpers). Imported FIRST so the per-domain modules can register
# their tools against the same mcp instance.
from homelab_mcp._runtime import mcp

# Domain modules — each defines @mcp.tool() functions at module scope, so
# importing the module is enough to register them. ``noqa: F401`` because
# the imports are intentional for their side effects.
from homelab_mcp.tools import platform  # noqa: F401
from homelab_mcp.tools import media  # noqa: F401
from homelab_mcp.tools import network  # noqa: F401
from homelab_mcp.tools import homeauto  # noqa: F401
from homelab_mcp.tools import control  # noqa: F401


def main() -> None:
    """Run the FastMCP server in stdio mode."""
    mcp.run()


if __name__ == "__main__":
    main()
